CREATE TABLE lm_CategoryTypes (
    id INT AUTO_INCREMENT PRIMARY KEY,
    code VARCHAR(2) UNIQUE NULL,
    name VARCHAR(255) NOT NULL,
    notes TEXT NULL,
    create_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE lm_Categories (
    id INT AUTO_INCREMENT PRIMARY KEY,
    category_types_id INT NOT NULL,
    code VARCHAR(2) UNIQUE NULL,
    name VARCHAR(255) NOT NULL,
    notes TEXT NULL,
    create_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (categoryTypeId) REFERENCES lm_CategoryTypes(id)
);
