DELETE FROM lmgc_Nationalities;

INSERT INTO lmgc_Nationalities (name, name_italian, name_french, name_spanish, name_german, name_portuguese, note, continent_id) VALUES
('Algerian', 'Algerino', 'Algérien', 'Argelino', 'Algerisch', 'Argelino', 'Nationality of Algeria', 1),
('Angolan', 'Angolano', 'Angolais', 'Angoleño', 'Angolanisch', 'Angolano', 'Nationality of Angola', 1),
('Beninese', 'Beninese', 'Béninois', 'Beninés', 'Beninisch', 'Beninense', 'Nationality of Benin', 1),
('Botswanan', 'Botswano', 'Botswanais', 'Botswano', 'Botswanisch', 'Botsuano', 'Nationality of Botswana', 1),
('Burkinabe', 'Burkinabé', 'Burkinabé', 'Burkinés', 'Burkinabisch', 'Burquinense', 'Nationality of Burkina Faso', 1),
('Burundian', 'Burundese', 'Burundais', 'Burundés', 'Burundisch', 'Burundês', 'Nationality of Burundi', 1),
('Cabo Verdean', 'Capoverdiano', 'Capverdien', 'Caboverdiano', 'Kapverdisch', 'Cabo-verdiano', 'Nationality of Cape Verde', 1),
('Cameroonian', 'Camerunense', 'Camerounais', 'Camerunés', 'Camerunisch', 'Camaronês', 'Nationality of Cameroon', 1),
('Central African', 'Centrafricano', 'Centrafricain', 'Centroafricano', 'Zentralafrikanisch', 'Centro-africano', 'Nationality of Central African Republic', 1),
('Chadian', 'Ciadiano', 'Tchadien', 'Chadiano', 'Tschadisch', 'Chadiano', 'Nationality of Chad', 1),
('Comorian', 'Comoriano', 'Comorien', 'Comorense', 'Komorisch', 'Comorense', 'Nationality of Comoros', 1),
('Congolese', 'Congolese', 'Congolais', 'Congoleño', 'Kongolesisch', 'Congolês', 'Nationality of Congo', 1),
('Djiboutian', 'Gibutiano', 'Djiboutien', 'Yibutiano', 'Dschibutisch', 'Djibutiano', 'Nationality of Djibouti', 1),
('Egyptian', 'Egiziano', 'Égyptien', 'Egipcio', 'Ägyptisch', 'Egípcio', 'Nationality of Egypt', 1),
('Equatorial Guinean', 'Guineano Equatoriale', 'Guinéen Équatorial', 'Guineano Ecuatorial', 'Äquatorialguineisch', 'Guineano-Equatorial', 'Nationality of Equatorial Guinea', 1),
('Eritrean', 'Eritreo', 'Érythréen', 'Eritreo', 'Eritreisch', 'Eritreu', 'Nationality of Eritrea', 1),
('Eswatini', 'Swazilandese', 'Swazi', 'Suazi', 'Swasisch', 'Suázi', 'Nationality of Eswatini', 1),
('Ethiopian', 'Ethiopico', 'Éthiopien', 'Etíope', 'Äthiopisch', 'Etíope', 'Nationality of Ethiopia', 1),
('Gabonese', 'Gabonese', 'Gabonais', 'Gabonés', 'Gabonisch', 'Gabonês', 'Nationality of Gabon', 1),
('Gambian', 'Gambiano', 'Gambien', 'Gambiano', 'Gambisch', 'Gambiano', 'Nationality of Gambia', 1),
('Ghanaian', 'Ghanese', 'Ghanéen', 'Ghanés', 'Ghanaisch', 'Ghanês', 'Nationality of Ghana', 1),
('Guinean', 'Guineano', 'Guinéen', 'Guineano', 'Guineisch', 'Guineano', 'Nationality of Guinea', 1),
('Ivory Coast', 'Ivory Coast', 'Ivoirien', 'Costamarfileño', 'Elfenbeinküstisch', 'Costa-marfinense', 'Nationality of Côte d\'Ivoire', 1),
('Kenyan', 'Keniota', 'Kényan', 'Keniata', 'Keniatisch', 'Queniano', 'Nationality of Kenya', 1),
('Lesotho', 'Lesothano', 'Lesothien', 'Lesoteño', 'Lesothisch', 'Lesotense', 'Nationality of Lesotho', 1),
('Liberian', 'Liberiano', 'Libérien', 'Liberiano', 'Liberianisch', 'Liberiano', 'Nationality of Liberia', 1),
('Libyan', 'Libico', 'Libyen', 'Libio', 'Libysch', 'Líbio', 'Nationality of Libya', 1),
('Madagascan', 'Madagassiano', 'Malgache', 'Malgache', 'Madagassisch', 'Malgaxe', 'Nationality of Madagascar', 1),
('Malawian', 'Malawiano', 'Malawien', 'Malauí', 'Malawisch', 'Malawiano', 'Nationality of Malawi', 1),
('Malian', 'Maliano', 'Malien', 'Maliense', 'Malisch', 'Maliano', 'Nationality of Mali', 1),
('Mauritanian', 'Mauritano', 'Mauritanien', 'Mauritano', 'Mauretanisch', 'Mauritano', 'Nationality of Mauritania', 1),
('Mauritian', 'Mauriziano', 'Mauricien', 'Mauriciano', 'Maurizianisch', 'Mauriciano', 'Nationality of Mauritius', 1),
('Moroccan', 'Marocchino', 'Marocain', 'Marroquí', 'Marokkanisch', 'Marroquino', 'Nationality of Morocco', 1),
('Mozambican', 'Mozambicano', 'Mozambicain', 'Mozambiqueño', 'Mosambikanisch', 'Moçambicano', 'Nationality of Mozambique', 1),
('Namibian', 'Namibiano', 'Namibien', 'Namibio', 'Namibisch', 'Namibiano', 'Nationality of Namibia', 1),
('Nigerien', 'Nigerino', 'Nigérien', 'Nigerino', 'Nigerisch', 'Nigerino', 'Nationality of Niger', 1),
('Nigerian', 'Nigeriano', 'Nigérian', 'Nigeriano', 'Nigerianisch', 'Nigeriano', 'Nationality of Nigeria', 1),
('Rwandan', 'Ruandese', 'Rwandais', 'Ruandés', 'Ruandisch', 'Rwandês', 'Nationality of Rwanda', 1),
('Sao Tomean', 'Sao-tomense', 'Sao-toméen', 'Santo-tomense', 'São-tomense', 'São-tomense', 'Nationality of São Tomé and Príncipe', 1),
('Senegalese', 'Senegalese', 'Sénégalais', 'Senegalés', 'Senegalesisch', 'Senegalês', 'Nationality of Senegal', 1),
('Seychellois', 'Seychellese', 'Seychellois', 'Seychelense', 'Seychellisch', 'Seychellense', 'Nationality of Seychelles', 1),
('Sierra Leonean', 'Sierra-leonese', 'Sierra-léonais', 'Sierra-leonés', 'Sierra-leonisch', 'Sierra-leonês', 'Nationality of Sierra Leone', 1),
('Somali', 'Somalo', 'Somalien', 'Somalí', 'Somalisch', 'Somali', 'Nationality of Somalia', 1),
('South African', 'Sudafricano', 'Sud-africain', 'Sudafricano', 'Südafrikanisch', 'Sul-africano', 'Nationality of South Africa', 1),
('South Sudanese', 'Sudanese del Sud', 'Soudanais du Sud', 'Sudanés del Sur', 'Südsudanesisch', 'Sudanês do Sul', 'Nationality of South Sudan', 1),
('Sudanese', 'Sudanese', 'Soudanais', 'Sudanés', 'Sudanesisch', 'Sudanês', 'Nationality of Sudan', 1),
('Tanzanian', 'Tanzaniano', 'Tanzanien', 'Tanzano', 'Tansanisch', 'Tanzaniano', 'Nationality of Tanzania', 1),
('Togolese', 'Togolese', 'Togolais', 'Togoleño', 'Togolesisch', 'Togolês', 'Nationality of Togo', 1),
('Tunisian', 'Tunisino', 'Tunisien', 'Tunecino', 'Tunesisch', 'Tunisino', 'Nationality of Tunisia', 1),
('Ugandan', 'Ugandese', 'Ougandais', 'Ugandés', 'Ugandisch', 'Ugandês', 'Nationality of Uganda', 1),
('Zambian', 'Zambiano', 'Zambien', 'Zambiano', 'Sambisch', 'Zambiano', 'Nationality of Zambia', 1),
('Zimbabwean', 'Zimbabwese', 'Zimbabwéen', 'Zimbabuense', 'Simbabweisch', 'Zimbabuense', 'Nationality of Zimbabwe', 1);

INSERT INTO lmgc_Nationalities (name, name_italian, name_french, name_spanish, name_german, name_portuguese, note, continent_id) VALUES
('Antarctic', 'Antartico', 'Antarctique', 'Antártico', 'Antarktisch', 'Antártico', 'Refers to the continent of Antarctica', 2);

INSERT INTO lmgc_Nationalities (name, name_italian, name_french, name_spanish, name_german, name_portuguese, note, continent_id) VALUES
('Afghan', 'Afghano', 'Afghan', 'Afgano', 'Afghanisch', 'Afgão', 'Nationality of Afghanistan', 3),
('Armenian', 'Armeno', 'Arménien', 'Armenio', 'Armenisch', 'Armênio', 'Nationality of Armenia', 3),
('Azerbaijani', 'Azerbaigiano', 'Azerbaïdjanais', 'Azerbaiyano', 'Aserbaidschanisch', 'Azerbaijano', 'Nationality of Azerbaijan', 3),
('Bahraini', 'Bahrainita', 'Bahreïnien', 'Bareiní', 'Bahrainisch', 'Bahrainita', 'Nationality of Bahrain', 3),
('Bangladeshi', 'Bangladese', 'Bangladais', 'Bangladesí', 'Bangladeschisch', 'Bangladês', 'Nationality of Bangladesh', 3),
('Bhutanese', 'Bhutanese', 'Bhoutanais', 'Butanés', 'Bhutanisch', 'Butanês', 'Nationality of Bhutan', 3),
('Brunei', 'Bruneano', 'Brunéien', 'Bruneano', 'Bruneisch', 'Bruneano', 'Nationality of Brunei', 3),
('Burma', 'Birmano', 'Birman', 'Birmana', 'Birmanisch', 'Birmanês', 'Nationality of Myanmar', 3),
('Cambodian', 'Cambogiano', 'Cambodgien', 'Camboyano', 'Kambodschanisch', 'Cambodjano', 'Nationality of Cambodia', 3),
('Chinese', 'Cinese', 'Chinois', 'Chino', 'Chinesisch', 'Chinês', 'Nationality of China', 3),
('Cypriot', 'Cipriota', 'Chypriote', 'Chipriota', 'Zyprisch', 'Chipriota', 'Nationality of Cyprus', 3),
('Georgian', 'Georgiano', 'Géorgien', 'Georgiano', 'Georgisch', 'Georgiano', 'Nationality of Georgia', 3),
('Indian', 'Indiano', 'Indien', 'Indio', 'Indisch', 'Indiano', 'Nationality of India', 3),
('Indonesian', 'Indonesiano', 'Indonésien', 'Indonesio', 'Indonesisch', 'Indonésio', 'Nationality of Indonesia', 3),
('Iranian', 'Iraniano', 'Iranien', 'Iraní', 'Iranisch', 'Iraniano', 'Nationality of Iran', 3),
('Iraqi', 'Irakeno', 'Irakien', 'Irakí', 'Irakisch', 'Iraquiano', 'Nationality of Iraq', 3),
('Israeli', 'Israeliano', 'Israélien', 'Israelí', 'Israelisch', 'Israelense', 'Nationality of Israel', 3),
('Japanese', 'Giapponese', 'Japonais', 'Japonés', 'Japanisch', 'Japonês', 'Nationality of Japan', 3),
('Jordanian', 'Giordano', 'Jordannien', 'Jordano', 'Jordanisch', 'Jordano', 'Nationality of Jordan', 3),
('Kazakh', 'Kazako', 'Kazakh', 'Kazajo', 'Kasachisch', 'Cazaque', 'Nationality of Kazakhstan', 3),
('Kuwaiti', 'Kuwaitiano', 'Koweïtien', 'Kuwaití', 'Kuwaitisch', 'Kuwaitiano', 'Nationality of Kuwait', 3),
('Kyrgyz', 'Kirghiso', 'Kirghize', 'Kirguís', 'Kirgisisch', 'Quirguiz', 'Nationality of Kyrgyzstan', 3),
('Laotian', 'Laotiano', 'Laotien', 'Laosiano', 'Laotisch', 'Laosiano', 'Nationality of Laos', 3),
('Lebanese', 'Libanese', 'Libanais', 'Libanés', 'Libanesisch', 'Libanês', 'Nationality of Lebanon', 3),
('Malaysian', 'Malese', 'Malaisien', 'Malasio', 'Malaysisch', 'Malaio', 'Nationality of Malaysia', 3),
('Maldivian', 'Maldiviano', 'Maldivien', 'Maldivo', 'Maldivisch', 'Maldivo', 'Nationality of Maldives', 3),
('Mongolian', 'Mongolo', 'Mongol', 'Mongol', 'Mongolisch', 'Mongol', 'Nationality of Mongolia', 3),
('Nepalese', 'Nepalese', 'Népalais', 'Nepalí', 'Nepalesisch', 'Nepalês', 'Nationality of Nepal', 3),
('Omani', 'Omanita', 'Omanais', 'Omaní', 'Omanisch', 'Omanita', 'Nationality of Oman', 3),
('Pakistani', 'Pakistano', 'Pakistanais', 'Paquistaní', 'Pakistani', 'Paquistanês', 'Nationality of Pakistan', 3),
('Palestinian', 'Palestinese', 'Palestinien', 'Palestino', 'Palästinensisch', 'Palestino', 'Nationality of Palestine', 3),
('Philippine', 'Filippino', 'Philippin', 'Filipino', 'Philippinisch', 'Filipino', 'Nationality of Philippines', 3),
('Qatari', 'Qatariano', 'Qatari', 'Qatarí', 'Katarisch', 'Qatariano', 'Nationality of Qatar', 3),
('Saudi Arabian', 'Arabo Saudita', 'Saoudien', 'Saudi', 'Saudisch', 'Saudita', 'Nationality of Saudi Arabia', 3),
('Singaporean', 'Singaporeano', 'Singapourien', 'Singapurense', 'Singapurisch', 'Cingapurense', 'Nationality of Singapore', 3),
('South Korean', 'Coreano del Sud', 'Coréen du Sud', 'Surcoreano', 'Südkoreanisch', 'Sul-coreano', 'Nationality of South Korea', 3),
('Sri Lankan', 'Sri Lankese', 'Srilankais', 'Sri Lanka', 'Sri-lankisch', 'Sri-lankês', 'Nationality of Sri Lanka', 3),
('Syrian', 'Siriano', 'Syrien', 'Sirio', 'Syrisch', 'Sírio', 'Nationality of Syria', 3),
('Tajik', 'Tagico', 'Tadjik', 'Tayiko', 'Tadschikisch', 'Tajique', 'Nationality of Tajikistan', 3),
('Thai', 'Tailandese', 'Thaïlandais', 'Tailandés', 'Thailändisch', 'Tailandês', 'Nationality of Thailand', 3),
('Turkmen', 'Turcomanno', 'Turkmène', 'Turcomano', 'Turkmensch', 'Turcomano', 'Nationality of Turkmenistan', 3),
('Uzbek', 'Uzbeko', 'Ouzbek', 'Uzbeco', 'Usbekisch', 'Uzbeque', 'Nationality of Uzbekistan', 3),
('Vietnamese', 'Vietnamita', 'Vietnamien', 'Vietnamita', 'Vietnamesisch', 'Vietnamita', 'Nationality of Vietnam', 3);

INSERT INTO lmgc_Nationalities (name, name_italian, name_french, name_spanish, name_german, name_portuguese, note, continent_id) VALUES
('Albanian', 'Albanese', 'Albanais', 'Albanés', 'Albanisch', 'Albanês', 'Nationality of Albania', 4),
('Andorran', 'Andorrano', 'Andorran', 'Andorrano', 'Andorranisch', 'Andorrano', 'Nationality of Andorra', 4),
('Austrian', 'Austriaco', 'Autrichien', 'Austriaco', 'Österreichisch', 'Austriaco', 'Nationality of Austria', 4),
('Belgian', 'Belga', 'Belge', 'Belga', 'Belgisch', 'Belga', 'Nationality of Belgium', 4),
('Bosnian', 'Bosniaco', 'Bosnien', 'Bosnio', 'Bosnisch', 'Bósnio', 'Nationality of Bosnia and Herzegovina', 4),
('Bulgarian', 'Bulgaro', 'Bulgare', 'Búlgaro', 'Bulgarisch', 'Búlgaro', 'Nationality of Bulgaria', 4),
('Croatian', 'Croato', 'Croate', 'Croata', 'Kroatisch', 'Croata', 'Nationality of Croatia', 4),
('Cypriot', 'Cipriota', 'Chypriote', 'Chipriota', 'Zyprisch', 'Chipriota', 'Nationality of Cyprus', 4),
('Czech', 'Ceco', 'Tchèque', 'Checo', 'Tschechisch', 'Checo', 'Nationality of Czech Republic', 4),
('Danish', 'Danese', 'Danois', 'Danés', 'Dänisch', 'Dinamarquês', 'Nationality of Denmark', 4),
('Dutch', 'Olandese', 'Néerlandais', 'Neerlandés', 'Niederländisch', 'Neerlandês', 'Nationality of Netherlands', 4),
('English', 'Inglese', 'Anglais', 'Inglés', 'Englisch', 'Inglês', 'Nationality of England', 4),
('Estonian', 'Estone', 'Estonien', 'Estonio', 'Estnisch', 'Estoniano', 'Nationality of Estonia', 4),
('Finnish', 'Finlandese', 'Finlandais', 'Finlandés', 'Finnisch', 'Finlandês', 'Nationality of Finland', 4),
('French', 'Francese', 'Français', 'Francés', 'Französisch', 'Francês', 'Nationality of France', 4),
('German', 'Tedesco', 'Allemand', 'Alemán', 'Deutsch', 'Alemão', 'Nationality of Germany', 4),
('Greek', 'Greco', 'Grec', 'Griego', 'Griechisch', 'Grego', 'Nationality of Greece', 4),
('Hungarian', 'Ungherese', 'Hongrois', 'Húngaro', 'Ungarisch', 'Húngaro', 'Nationality of Hungary', 4),
('Icelandic', 'Islandese', 'Islandais', 'Islandés', 'Isländisch', 'Islandês', 'Nationality of Iceland', 4),
('Irish', 'Irlandese', 'Irlandais', 'Irlandés', 'Irisch', 'Irlandês', 'Nationality of Ireland', 4),
('Italian', 'Italiano', 'Italien', 'Italiano', 'Italienisch', 'Italiano', 'Nationality of Italy', 4),
('Latvian', 'Lettone', 'Letton', 'Letón', 'Lettisch', 'Letão', 'Nationality of Latvia', 4),
('Liechtenstein', 'Liechtensteiniano', 'Liechtensteinois', 'Liechtensteinense', 'Liechtensteinisch', 'Liechtensteiniano', 'Nationality of Liechtenstein', 4),
('Lithuanian', 'Lituano', 'Lituanien', 'Lituano', 'Litauisch', 'Lituano', 'Nationality of Lithuania', 4),
('Luxembourgish', 'Lussemburghese', 'Luxembourgeois', 'Luxemburgués', 'Luxemburgisch', 'Luxemburguês', 'Nationality of Luxembourg', 4),
('Malta', 'Maltese', 'Maltais', 'Maltés', 'Maltesisch', 'Maltês', 'Nationality of Malta', 4),
('Moldovan', 'Moldavo', 'Moldave', 'Moldavo', 'Moldawisch', 'Moldavo', 'Nationality of Moldova', 4),
('Monaco', 'Monégasque', 'Monégasque', 'Monegasco', 'Monegassisch', 'Monegasco', 'Nationality of Monaco', 4),
('Montenegrin', 'Montenegrino', 'Monténégrin', 'Montenegrino', 'Montenegrinisch', 'Montenegrino', 'Nationality of Montenegro', 4),
('North Macedonian', 'Macedone del Nord', 'Macédonien', 'Macedonio', 'Nordmazedonisch', 'Macedônio', 'Nationality of North Macedonia', 4),
('Norwegian', 'Norvegese', 'Norvégien', 'Noruego', 'Norwegisch', 'Norueguês', 'Nationality of Norway', 4),
('Polish', 'Polacco', 'Polonais', 'Polaco', 'Polnisch', 'Polonês', 'Nationality of Poland', 4),
('Portuguese', 'Portoghese', 'Portugais', 'Portugués', 'Portugiesisch', 'Português', 'Nationality of Portugal', 4),
('Romanian', 'Rumeno', 'Roumain', 'Rumano', 'Rumänisch', 'Romeno', 'Nationality of Romania', 4),
('Russian', 'Russo', 'Russe', 'Ruso', 'Russisch', 'Russo', 'Nationality of Russia', 4),
('San Marinese', 'Sammarinese', 'Saint-Marinais', 'Sammarinese', 'Sammarinesisch', 'Sammarinese', 'Nationality of San Marino', 4),
('Serbian', 'Serbo', 'Serbe', 'Serbio', 'Serbisch', 'Sérvio', 'Nationality of Serbia', 4),
('Slovak', 'Slovacco', 'Slovaque', 'Eslovaco', 'Slowakisch', 'Eslovaco', 'Nationality of Slovakia', 4),
('Slovenian', 'Sloveno', 'Slovène', 'Esloveno', 'Slowenisch', 'Esloveno', 'Nationality of Slovenia', 4),
('Spanish', 'Spagnolo', 'Espagnol', 'Español', 'Spanisch', 'Espanhol', 'Nationality of Spain', 4),
('Swedish', 'Svedese', 'Suédois', 'Sueco', 'Schwedisch', 'Sueco', 'Nationality of Sweden', 4),
('Swiss', 'Svizzero', 'Suisse', 'Suizo', 'Schweizerisch', 'Suíço', 'Nationality of Switzerland', 4),
('Turkish', 'Turco', 'Turc', 'Turco', 'Türkisch', 'Turco', 'Nationality of Turkey', 4),
('Ukrainian', 'Ucraino', 'Ukrainien', 'Ucraniano', 'Ukrainisch', 'Ucraniano', 'Nationality of Ukraine', 4),
('Vatican', 'Vaticano', 'Vatican', 'Vaticano', 'Vatikansich', 'Vaticano', 'Nationality of Vatican City', 4);
