DROP TABLE IF EXISTS lmgc_Cities;
DROP TABLE IF EXISTS lmgc_Countries;
DROP TABLE IF EXISTS lmgc_Continents;

CREATE TABLE IF NOT EXISTS lmgc_Continents (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    code VARCHAR(10) NOT NULL UNIQUE,
    surface_area DECIMAL(15, 2),
    population BIGINT,
    num_countries INT,
    description TEXT,
    notes TEXT,
    name_italian VARCHAR(100) UNIQUE,
    name_english VARCHAR(100) UNIQUE,
    name_french VARCHAR(100) UNIQUE,
    name_german VARCHAR(100) UNIQUE,
    name_spanish VARCHAR(100) UNIQUE,
    name_portuguese VARCHAR(100) UNIQUE,
    creation_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

INSERT INTO lmgc_Continents (name, code, surface_area, population, num_countries, description, notes, name_italian, name_english, name_french, name_german, name_spanish, name_portuguese) VALUES
('Africa', 'AF', 30370000.00, 1340598000, 54, 'Secondo continente per superficie e popolazione.', 'Note su Africa', 'Africa', 'Africa', 'Afrique', 'Afrika', 'África', 'África'),
('Antarctica', 'AN', 14000000.00, 1106, 0, 'Continent primarily covered by ice.', 'Note su Antarctica', 'Antartide', 'Antarctica', 'Antarctique', 'Antarktis', 'Antártida', 'Antártica'),
('Asia', 'AS', 44579000.00, 4641054775, 49, 'Largest continent by both area and population.', 'Note su Asia', 'Asia', 'Asia', 'Asie', 'Asien', 'Asia', 'Ásia'),
('Europe', 'EU', 10180000.00, 747636026, 44, 'Home to many countries and diverse cultures.', 'Note su Europe', 'Europa', 'Europe', 'Europe', 'Europa', 'Europa', 'Europa'),
('North America', 'NA', 24709000.00, 592072212, 23, 'Includes Canada, USA, Mexico, and Central America.', 'Note su North America', 'America del Nord', 'North America', 'Amérique du Nord', 'Nordamerika', 'América del Norte', 'América do Norte'),
('Oceania', 'OC', 8600000.00, 43111704, 14, 'Includes Australia, New Zealand, and many Pacific islands.', 'Note su Oceania', 'Oceania', 'Oceania', 'Océanie', 'Ozeanien', 'Oceanía', 'Oceania'),
('South America', 'SA', 17840000.00, 430759766, 12, 'Known for the Amazon rainforest and Andes mountains.', 'Note su South America', 'America del Sud', 'South America', 'Amérique du Sud', 'Südamerika', 'América del Sur', 'América do Sul');

CREATE TABLE IF NOT EXISTS lmgc_Countries (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    continent_id INT NOT NULL,
    description TEXT,
    notes TEXT,
    iso_alpha_2 CHAR(2) UNIQUE,
    iso_alpha_3 CHAR(3) UNIQUE,
    iso_numeric CHAR(3) UNIQUE,
    image_path VARCHAR(255),
    suspended BOOLEAN DEFAULT FALSE,
    name_italian VARCHAR(100) UNIQUE,
    name_english VARCHAR(100) UNIQUE,
    name_french VARCHAR(100) UNIQUE,
    name_german VARCHAR(100) UNIQUE,
    name_spanish VARCHAR(100) UNIQUE,
    name_portuguese VARCHAR(100) UNIQUE,
    creation_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (continent_id) REFERENCES lmgc_Continents(id)
);

INSERT INTO lmgc_Countries (name, continent_id, description, notes, iso_alpha_2, iso_alpha_3, iso_numeric, image_path, suspended, name_italian, name_english, name_french, name_german, name_spanish, name_portuguese) VALUES
('Algeria', 1, 'Stato dell\'Africa settentrionale.', 'Note su Algeria', 'DZ', 'DZA', '012', 'path/to/algeria.png', FALSE, 'Algeria', 'Algeria', 'Algérie', 'Algerien', 'Argelia', 'Argélia'),
('Angola', 1, 'Stato dell\'Africa centrale.', 'Note su Angola', 'AO', 'AGO', '024', 'path/to/angola.png', FALSE, 'Angola', 'Angola', 'Angola', 'Angola', 'Angola', 'Angola'),
('Benin', 1, 'Stato dell\'Africa occidentale.', 'Note su Benin', 'BJ', 'BEN', '204', 'path/to/benin.png', FALSE, 'Benin', 'Benin', 'Bénin', 'Benin', 'Benín', 'Benim'),
('Botswana', 1, 'Stato dell\'Africa australe.', 'Note su Botswana', 'BW', 'BWA', '072', 'path/to/botswana.png', FALSE, 'Botswana', 'Botswana', 'Botswana', 'Botsuana', 'Botsuana', 'Botsuana'),
('Burkina Faso', 1, 'Stato dell\'Africa occidentale.', 'Note su Burkina Faso', 'BF', 'BFA', '854', 'path/to/burkina_faso.png', FALSE, 'Burkina Faso', 'Burkina Faso', 'Burkina Faso', 'Burkina Faso', 'Burkina Faso', 'Burkina Faso'),
('Burundi', 1, 'Stato dell\'Africa orientale.', 'Note su Burundi', 'BI', 'BDI', '108', 'path/to/burundi.png', FALSE, 'Burundi', 'Burundi', 'Burundi', 'Burundi', 'Burundi', 'Burundi'),
('Cabo Verde', 1, 'Stato insulare dell\'Africa occidentale.', 'Note su Cabo Verde', 'CV', 'CPV', '132', 'path/to/cabo_verde.png', FALSE, 'Capo Verde', 'Cabo Verde', 'Cap-Vert', 'Kap Verde', 'Cabo Verde', 'Cabo Verde'),
('Cameroon', 1, 'Stato dell\'Africa centrale.', 'Note su Cameroon', 'CM', 'CMR', '120', 'path/to/cameroon.png', FALSE, 'Camerun', 'Cameroon', 'Cameroun', 'Kamerun', 'Camerún', 'Camarões'),
('Central African Republic', 1, 'Stato dell\'Africa centrale.', 'Note su Central African Republic', 'CF', 'CAF', '140', 'path/to/central_african_republic.png', FALSE, 'Repubblica Centrafricana', 'Central African Republic', 'République centrafricaine', 'Zentralafrikanische Republik', 'República Centroafricana', 'República Centro-Africana'),
('Chad', 1, 'Stato dell\'Africa centrale.', 'Note su Chad', 'TD', 'TCD', '148', 'path/to/chad.png', FALSE, 'Ciad', 'Chad', 'Tchad', 'Tschad', 'Chad', 'Chade'),
('Comoros', 1, 'Stato insulare dell\'Africa orientale.', 'Note su Comoros', 'KM', 'COM', '174', 'path/to/comoros.png', FALSE, 'Comore', 'Comoros', 'Comores', 'Komoren', 'Comoras', 'Comores'),
('Congo, Democratic Republic of the', 1, 'Stato dell\'Africa centrale.', 'Note su Democratic Republic of the Congo', 'CD', 'COD', '180', 'path/to/democratic_republic_of_the_congo.png', FALSE, 'Repubblica Democratica del Congo', 'Democratic Republic of the Congo', 'République démocratique du Congo', 'Demokratische Republik Kongo', 'República Democrática del Congo', 'República Democrática do Congo'),
('Congo, Republic of the', 1, 'Stato dell\'Africa centrale.', 'Note su Republic of the Congo', 'CG', 'COG', '178', 'path/to/republic_of_the_congo.png', FALSE, 'Congo', 'Congo', 'Congo', 'Kongo', 'Congo', 'Congo'),
('Djibouti', 1, 'Stato dell\'Africa orientale.', 'Note su Djibouti', 'DJ', 'DJI', '262', 'path/to/djibouti.png', FALSE, 'Gibuti', 'Djibouti', 'Djibouti', 'Dschibuti', 'Yibuti', 'Djibuti'),
('Egypt', 1, 'Stato dell\'Africa nord-orientale.', 'Note su Egypt', 'EG', 'EGY', '818', 'path/to/egypt.png', FALSE, 'Egitto', 'Egypt', 'Égypte', 'Ägypten', 'Egipto', 'Egito'),
('Equatorial Guinea', 1, 'Stato dell\'Africa centrale.', 'Note su Equatorial Guinea', 'GQ', 'GNQ', '226', 'path/to/equatorial_guinea.png', FALSE, 'Guinea Equatoriale', 'Equatorial Guinea', 'Guinée équatoriale', 'Äquatorialguinea', 'Guinea Ecuatorial', 'Guinéu Equatorial'),
('Eritrea', 1, 'Stato dell\'Africa orientale.', 'Note su Eritrea', 'ER', 'ERI', '232', 'path/to/eritrea.png', FALSE, 'Eritrea', 'Eritrea', 'Érythrée', 'Eritrea', 'Eritrea', 'Eritreia'),
('Eswatini', 1, 'Stato dell\'Africa meridionale.', 'Note su Eswatini', 'SZ', 'SWZ', '748', 'path/to/eswatini.png', FALSE, 'Eswatini', 'Eswatini', 'Eswatini', 'Eswatini', 'Suazilandia', 'Essuatíni'),
('Ethiopia', 1, 'Stato dell\'Africa orientale.', 'Note su Ethiopia', 'ET', 'ETH', '231', 'path/to/ethiopia.png', FALSE, 'Etiopia', 'Ethiopia', 'Éthiopie', 'Äthiopien', 'Etiopía', 'Etiópia'),
('Gabon', 1, 'Stato dell\'Africa centrale.', 'Note su Gabon', 'GA', 'GAB', '266', 'path/to/gabon.png', FALSE, 'Gabon', 'Gabon', 'Gabon', 'Gabon', 'Gabón', 'Gabão'),
('Gambia', 1, 'Stato dell\'Africa occidentale.', 'Note su Gambia', 'GM', 'GMB', '270', 'path/to/gambia.png', FALSE, 'Gambia', 'Gambia', 'Gambie', 'Gambia', 'Gambia', 'Gâmbia'),
('Ghana', 1, 'Stato dell\'Africa occidentale.', 'Note su Ghana', 'GH', 'GHA', '288', 'path/to/ghana.png', FALSE, 'Ghana', 'Ghana', 'Ghana', 'Ghana', 'Ghana', 'Gana'),
('Guinea', 1, 'Stato dell\'Africa occidentale.', 'Note su Guinea', 'GN', 'GIN', '324', 'path/to/guinea.png', FALSE, 'Guinea', 'Guinea', 'Guinée', 'Guinea', 'Guinea', 'Guiné'),
('Guinea-Bissau', 1, 'Stato dell\'Africa occidentale.', 'Note su Guinea-Bissau', 'GW', 'GNB', '624', 'path/to/guinea_bissau.png', FALSE, 'Guinea-Bissau', 'Guinea-Bissau', 'Guinée-Bissau', 'Guinea-Bissau', 'Guinea-Bisáu', 'Guiné-Bissau'),
('Ivory Coast', 1, 'Stato dell\'Africa occidentale.', 'Note su Ivory Coast', 'CI', 'CIV', '384', 'path/to/ivory_coast.png', FALSE, 'Costa d\'Avorio', 'Ivory Coast', 'Côte d\'Ivoire', 'Elfenbeinküste', 'Costa de Marfil', 'Costa do Marfim'),
('Kenya', 1, 'Stato dell\'Africa orientale.', 'Note su Kenya', 'KE', 'KEN', '404', 'path/to/kenya.png', FALSE, 'Kenya', 'Kenya', 'Kenya', 'Kenia', 'Kenia', 'Quénia'),
('Lesotho', 1, 'Stato dell\'Africa meridionale.', 'Note su Lesotho', 'LS', 'LSO', '426', 'path/to/lesotho.png', FALSE, 'Lesotho', 'Lesotho', 'Lesotho', 'Lesotho', 'Lesoto', 'Lesoto'),
('Liberia', 1, 'Stato dell\'Africa occidentale.', 'Note su Liberia', 'LR', 'LBR', '430', 'path/to/liberia.png', FALSE, 'Liberia', 'Liberia', 'Liberia', 'Liberia', 'Liberia', 'Libéria'),
('Libya', 1, 'Stato dell\'Africa settentrionale.', 'Note su Libya', 'LY', 'LBY', '434', 'path/to/libya.png', FALSE, 'Libia', 'Libya', 'Libye', 'Libyen', 'Libia', 'Líbia'),
('Madagascar', 1, 'Isola dell\'Africa orientale.', 'Note su Madagascar', 'MG', 'MDG', '450', 'path/to/madagascar.png', FALSE, 'Madagascar', 'Madagascar', 'Madagascar', 'Madagaskar', 'Madagascar', 'Madagascar'),
('Malawi', 1, 'Stato dell\'Africa orientale.', 'Note su Malawi', 'MW', 'MWI', '454', 'path/to/malawi.png', FALSE, 'Malawi', 'Malawi', 'Malawi', 'Malawi', 'Malawi', 'Malawi'),
('Mali', 1, 'Stato dell\'Africa occidentale.', 'Note su Mali', 'ML', 'MLI', '466', 'path/to/mali.png', FALSE, 'Mali', 'Mali', 'Mali', 'Mali', 'Malí', 'Mali'),
('Mauritania', 1, 'Stato dell\'Africa occidentale.', 'Note su Mauritania', 'MR', 'MRT', '478', 'path/to/mauritania.png', FALSE, 'Mauritania', 'Mauritania', 'Mauritanie', 'Mauretanien', 'Mauritania', 'Mauritânia'),
('Mauritius', 1, 'Isola dell\'Africa orientale.', 'Note su Mauritius', 'MU', 'MUS', '480', 'path/to/mauritius.png', FALSE, 'Mauritius', 'Mauritius', 'Île Maurice', 'Mauritius', 'Mauricio', 'Maurício'),
('Morocco', 1, 'Stato dell\'Africa nord-occidentale.', 'Note su Morocco', 'MA', 'MAR', '504', 'path/to/morocco.png', FALSE, 'Marocco', 'Morocco', 'Maroc', 'Marokko', 'Marruecos', 'Marrocos'),
('Mozambique', 1, 'Stato dell\'Africa sud-orientale.', 'Note su Mozambique', 'MZ', 'MOZ', '508', 'path/to/mozambique.png', FALSE, 'Mozambico', 'Mozambique', 'Mozambique', 'Mosambik', 'Mozambique', 'Moçambique'),
('Namibia', 1, 'Stato dell\'Africa sud-occidentale.', 'Note su Namibia', 'NA', 'NAM', '516', 'path/to/namibia.png', FALSE, 'Namibia', 'Namibia', 'Namibie', 'Namibia', 'Namibia', 'Namíbia'),
('Niger', 1, 'Stato dell\'Africa occidentale.', 'Note su Niger', 'NE', 'NER', '562', 'path/to/niger.png', FALSE, 'Niger', 'Niger', 'Niger', 'Niger', 'Níger', 'Níger'),
('Nigeria', 1, 'Stato dell\'Africa occidentale.', 'Note su Nigeria', 'NG', 'NGA', '566', 'path/to/nigeria.png', FALSE, 'Nigeria', 'Nigeria', 'Nigéria', 'Nigeria', 'Nigeria', 'Nigéria'),
('Rwanda', 1, 'Stato dell\'Africa orientale.', 'Note su Rwanda', 'RW', 'RWA', '646', 'path/to/rwanda.png', FALSE, 'Ruanda', 'Rwanda', 'Rwanda', 'Ruanda', 'Ruanda', 'Ruanda'),
('Sao Tome and Principe', 1, 'Stato insulare dell\'Africa occidentale.', 'Note su Sao Tome and Principe', 'ST', 'STP', '678', 'path/to/sao_tome_and_principe.png', FALSE, 'São Tomé e Príncipe', 'São Tomé and Principe', 'São Tomé-et-Príncipe', 'São Tomé e Príncipe', 'Santo Tomé y Príncipe', 'São Tomé e Príncipe'),
('Senegal', 1, 'Stato dell\'Africa occidentale.', 'Note su Senegal', 'SN', 'SEN', '686', 'path/to/senegal.png', FALSE, 'Senegal', 'Senegal', 'Sénégal', 'Senegal', 'Senegal', 'Senegal'),
('Seychelles', 1, 'Stato insulare dell\'Africa orientale.', 'Note su Seychelles', 'SC', 'SYC', '690', 'path/to/seychelles.png', FALSE, 'Seychelles', 'Seychelles', 'Seychelles', 'Seychellen', 'Seychelles', 'Seicheles'),
('Sierra Leone', 1, 'Stato dell\'Africa occidentale.', 'Note su Sierra Leone', 'SL', 'SLE', '694', 'path/to/sierra_leone.png', FALSE, 'Sierra Leone', 'Sierra Leone', 'Sierra Leone', 'Sierra Leone', 'Sierra Leona', 'Serra Leoa'),
('Somalia', 1, 'Stato dell\'Africa orientale.', 'Note su Somalia', 'SO', 'SOM', '706', 'path/to/somalia.png', FALSE, 'Somalia', 'Somalia', 'Somalie', 'Somalia', 'Somalia', 'Somália'),
('South Sudan', 1, 'Stato dell\'Africa orientale.', 'Note su South Sudan', 'SS', 'SSD', '728', 'path/to/south_sudan.png', FALSE, 'Sud Sudan', 'South Sudan', 'Soudan du Sud', 'Südsudan', 'Sudán del Sur', 'Sudão do Sul'),
('Sudan', 1, 'Stato dell\'Africa nord-orientale.', 'Note su Sudan', 'SD', 'SDN', '729', 'path/to/sudan.png', FALSE, 'Sudan', 'Sudan', 'Soudan', 'Sudan', 'Sudán', 'Sudão'),
('Togo', 1, 'Stato dell\'Africa occidentale.', 'Note su Togo', 'TG', 'TGO', '768', 'path/to/togo.png', FALSE, 'Togo', 'Togo', 'Togo', 'Togo', 'Togo', 'Togo'),
('Tunisia', 1, 'Stato dell\'Africa settentrionale.', 'Note su Tunisia', 'TN', 'TUN', '788', 'path/to/tunisia.png', FALSE, 'Tunisia', 'Tunisia', 'Tunisie', 'Tunesien', 'Túnez', 'Tunísia'),
('Uganda', 1, 'Stato dell\'Africa orientale.', 'Note su Uganda', 'UG', 'UGA', '800', 'path/to/uganda.png', FALSE, 'Uganda', 'Uganda', 'Ouganda', 'Uganda', 'Uganda', 'Uganda'),
('United Republic of Tanzania', 1, 'Stato dell\'Africa orientale.', 'Note su Tanzania', 'TZ', 'TZA', '834', 'path/to/tanzania.png', FALSE, 'Tanzania', 'Tanzania', 'Tanzanie', 'Tansania', 'Tanzania', 'Tanzânia'),
('Zambia', 1, 'Stato dell\'Africa orientale.', 'Note su Zambia', 'ZM', 'ZMB', '894', 'path/to/zambia.png', FALSE, 'Zambia', 'Zambia', 'Zambie', 'Sambia', 'Zambia', 'Zâmbia'),
('Zimbabwe', 1, 'Stato dell\'Africa australe.', 'Note su Zimbabwe', 'ZW', 'ZWE', '716', 'path/to/zimbabwe.png', FALSE, 'Zimbabwe', 'Zimbabwe', 'Zimbabwe', 'Simbabwe', 'Zimbabue', 'Zimbábue');

INSERT INTO lmgc_Countries (name, continent_id, description, notes, iso_alpha_2, iso_alpha_3, iso_numeric, image_path, suspended, name_italian, name_english, name_french, name_german, name_spanish, name_portuguese) VALUES
('Antarctica', 2, 'Continent primarily covered by ice.', 'No sovereign states in Antarctica.', 'AQ', 'ATA', '010', 'path/to/antarctica.png', FALSE, 'Antartide', 'Antarctica', 'Antarctique', 'Antarktis', 'Antártida', 'Antártica');

INSERT INTO lmgc_Countries (name, continent_id, description, notes, iso_alpha_2, iso_alpha_3, iso_numeric, image_path, suspended, name_italian, name_english, name_french, name_german, name_spanish, name_portuguese) VALUES
('Afghanistan', 3, 'Stato dell\'Asia meridionale.', 'Note su Afghanistan', 'AF', 'AFG', '004', 'path/to/afghanistan.png', FALSE, 'Afghanistan', 'Afghanistan', 'Afghanistan', 'Afghanistan', 'Afganistán', 'Afeganistão'),
('Armenia', 3, 'Stato dell\'Asia occidentale.', 'Note su Armenia', 'AM', 'ARM', '051', 'path/to/armenia.png', FALSE, 'Armenia', 'Armenia', 'Arménie', 'Armenien', 'Armenia', 'Arménia'),
('Azerbaijan', 3, 'Stato dell\'Asia occidentale.', 'Note su Azerbaijan', 'AZ', 'AZE', '031', 'path/to/azerbaijan.png', FALSE, 'Azerbaigian', 'Azerbaijan', 'Azerbaïdjan', 'Aserbaidschan', 'Azerbaiyán', 'Azerbaijão'),
('Bahrain', 3, 'Stato dell\'Asia occidentale.', 'Note su Bahrain', 'BH', 'BHR', '048', 'path/to/bahrain.png', FALSE, 'Bahrein', 'Bahrain', 'Bahreïn', 'Bahrain', 'Baréin', 'Barém'),
('Bangladesh', 3, 'Stato dell\'Asia meridionale.', 'Note su Bangladesh', 'BD', 'BGD', '050', 'path/to/bangladesh.png', FALSE, 'Bangladesh', 'Bangladesh', 'Bangladesh', 'Bangladesch', 'Bangladés', 'Bangladesh'),
('Bhutan', 3, 'Stato dell\'Asia meridionale.', 'Note su Bhutan', 'BT', 'BTN', '064', 'path/to/bhutan.png', FALSE, 'Bhutan', 'Bhutan', 'Bhoutan', 'Bhutan', 'Bután', 'Butão'),
('Brunei', 3, 'Stato dell\'Asia sud-orientale.', 'Note su Brunei', 'BN', 'BRN', '096', 'path/to/brunei.png', FALSE, 'Brunei', 'Brunei', 'Brunei', 'Brunei', 'Brunéi', 'Brunei'),
('Cambodia', 3, 'Stato dell\'Asia sud-orientale.', 'Note su Cambodia', 'KH', 'KHM', '116', 'path/to/cambodia.png', FALSE, 'Cambogia', 'Cambodia', 'Cambodge', 'Kambodscha', 'Camboya', 'Camboja'),
('China', 3, 'Stato dell\'Asia orientale.', 'Note su China', 'CN', 'CHN', '156', 'path/to/china.png', FALSE, 'Cina', 'China', 'Chine', 'China', 'China', 'China'),
('Cyprus', 3, 'Stato insulare dell\'Asia orientale.', 'Note su Cyprus', 'CY', 'CYP', '196', 'path/to/cyprus.png', FALSE, 'Cipro', 'Cyprus', 'Chypre', 'Zypern', 'Chipre', 'Chipre'),
('Georgia', 3, 'Stato dell\'Asia occidentale.', 'Note su Georgia', 'GE', 'GEO', '268', 'path/to/georgia.png', FALSE, 'Georgia', 'Georgia', 'Géorgie', 'Georgien', 'Georgia', 'Geórgia'),
('India', 3, 'Stato dell\'Asia meridionale.', 'Note su India', 'IN', 'IND', '356', 'path/to/india.png', FALSE, 'India', 'India', 'Inde', 'Indien', 'India', 'Índia'),
('Indonesia', 3, 'Stato dell\'Asia sud-orientale.', 'Note su Indonesia', 'ID', 'IDN', '360', 'path/to/indonesia.png', FALSE, 'Indonesia', 'Indonesia', 'Indonésie', 'Indonesien', 'Indonesia', 'Indonésia'),
('Iran', 3, 'Stato dell\'Asia sud-occidentale.', 'Note su Iran', 'IR', 'IRN', '364', 'path/to/iran.png', FALSE, 'Iran', 'Iran', 'Iran', 'Iran', 'Irán', 'Irã'),
('Iraq', 3, 'Stato dell\'Asia sud-occidentale.', 'Note su Iraq', 'IQ', 'IRQ', '368', 'path/to/iraq.png', FALSE, 'Iraq', 'Iraq', 'Irak', 'Irak', 'Irak', 'Iraque'),
('Israel', 3, 'Stato dell\'Asia occidentale.', 'Note su Israel', 'IL', 'ISR', '376', 'path/to/israel.png', FALSE, 'Israele', 'Israel', 'Israël', 'Israel', 'Israel', 'Israel'),
('Japan', 3, 'Stato dell\'Asia orientale.', 'Note su Japan', 'JP', 'JPN', '392', 'path/to/japan.png', FALSE, 'Giappone', 'Japan', 'Japon', 'Japan', 'Japón', 'Japão'),
('Jordan', 3, 'Stato dell\'Asia sud-occidentale.', 'Note su Jordan', 'JO', 'JOR', '400', 'path/to/jordan.png', FALSE, 'Giordania', 'Jordan', 'Jordanie', 'Jordanien', 'Jordania', 'Jordânia'),
('Kazakhstan', 3, 'Stato dell\'Asia centrale.', 'Note su Kazakhstan', 'KZ', 'KAZ', '398', 'path/to/kazakhstan.png', FALSE, 'Kazakistan', 'Kazakhstan', 'Kazakhstan', 'Kasachstan', 'Kazajistán', 'Cazaquistão'),
('Kuwait', 3, 'Stato dell\'Asia sud-occidentale.', 'Note su Kuwait', 'KW', 'KWT', '414', 'path/to/kuwait.png', FALSE, 'Kuwait', 'Kuwait', 'Koweït', 'Kuwait', 'Kuwait', 'Kuwait'),
('Kyrgyzstan', 3, 'Stato dell\'Asia centrale.', 'Note su Kyrgyzstan', 'KG', 'KGZ', '417', 'path/to/kyrgyzstan.png', FALSE, 'Kyrgyzistan', 'Kyrgyzstan', 'Kirghizistan', 'Kirgisistan', 'Kirguistán', 'Quirguistão'),
('Laos', 3, 'Stato dell\'Asia sud-orientale.', 'Note su Laos', 'LA', 'LAO', '418', 'path/to/laos.png', FALSE, 'Laos', 'Laos', 'Laos', 'Laos', 'Laos', 'Laos'),
('Lebanon', 3, 'Stato dell\'Asia sud-occidentale.', 'Note su Lebanon', 'LB', 'LBN', '422', 'path/to/lebanon.png', FALSE, 'Libano', 'Lebanon', 'Liban', 'Libanon', 'Líbano', 'Líbano'),
('Malaysia', 3, 'Stato dell\'Asia sud-orientale.', 'Note su Malaysia', 'MY', 'MYS', '458', 'path/to/malaysia.png', FALSE, 'Malesia', 'Malaysia', 'Malaisie', 'Malaysia', 'Malasia', 'Malásia'),
('Maldives', 3, 'Stato insulare dell\'Asia meridionale.', 'Note su Maldives', 'MV', 'MDV', '462', 'path/to/maldives.png', FALSE, 'Maldive', 'Maldives', 'Maldives', 'Maldiven', 'Maldivas', 'Maldivas'),
('Mongolia', 3, 'Stato dell\'Asia orientale.', 'Note su Mongolia', 'MN', 'MNG', '496', 'path/to/mongolia.png', FALSE, 'Mongolia', 'Mongolia', 'Mongolie', 'Mongolei', 'Mongolia', 'Mongólia'),
('Myanmar', 3, 'Stato dell\'Asia sud-orientale.', 'Note su Myanmar', 'MM', 'MMR', '104', 'path/to/myanmar.png', FALSE, 'Myanmar', 'Myanmar', 'Birmanie', 'Myanmar', 'Birmania', 'Myanmar'),
('Nepal', 3, 'Stato dell\'Asia meridionale.', 'Note su Nepal', 'NP', 'NPL', '524', 'path/to/nepal.png', FALSE, 'Nepal', 'Nepal', 'Népal', 'Nepal', 'Nepal', 'Nepal'),
('North Korea', 3, 'Stato dell\'Asia orientale.', 'Note su North Korea', 'KP', 'PRK', '408', 'path/to/north_korea.png', FALSE, 'Corea del Nord', 'North Korea', 'Corée du Nord', 'Nordkorea', 'Corea del Norte', 'Coreia do Norte'),
('Oman', 3, 'Stato dell\'Asia sud-occidentale.', 'Note su Oman', 'OM', 'OMN', '512', 'path/to/oman.png', FALSE, 'Oman', 'Oman', 'Oman', 'Oman', 'Omán', 'Oman'),
('Pakistan', 3, 'Stato dell\'Asia meridionale.', 'Note su Pakistan', 'PK', 'PAK', '586', 'path/to/pakistan.png', FALSE, 'Pakistan', 'Pakistan', 'Pakistan', 'Pakistan', 'Pakistán', 'Paquistão'),
('Palestine', 3, 'Territorio conteso dell\'Asia sud-occidentale.', 'Note su Palestine', 'PS', 'PSE', '275', 'path/to/palestine.png', FALSE, 'Palestina', 'Palestine', 'Palestine', 'Palästina', 'Palestina', 'Palestina'),
('Philippines', 3, 'Stato dell\'Asia sud-orientale.', 'Note su Philippines', 'PH', 'PHL', '608', 'path/to/philippines.png', FALSE, 'Filippine', 'Philippines', 'Philippines', 'Philippinen', 'Filipinas', 'Filipinas'),
('Qatar', 3, 'Stato dell\'Asia sud-occidentale.', 'Note su Qatar', 'QA', 'QAT', '634', 'path/to/qatar.png', FALSE, 'Qatar', 'Qatar', 'Qatar', 'Katar', 'Catar', 'Catar'),
('Saudi Arabia', 3, 'Stato dell\'Asia sud-occidentale.', 'Note su Saudi Arabia', 'SA', 'SAU', '682', 'path/to/saudi_arabia.png', FALSE, 'Arabia Saudita', 'Saudi Arabia', 'Arabie Saoudite', 'Saudi-Arabien', 'Arabia Saudita', 'Arábia Saudita'),
('Singapore', 3, 'Stato dell\'Asia sud-orientale.', 'Note su Singapore', 'SG', 'SGP', '702', 'path/to/singapore.png', FALSE, 'Singapore', 'Singapore', 'Singapour', 'Singapur', 'Singapur', 'Singapura'),
('South Korea', 3, 'Stato dell\'Asia orientale.', 'Note su South Korea', 'KR', 'KOR', '410', 'path/to/south_korea.png', FALSE, 'Corea del Sud', 'South Korea', 'Corée du Sud', 'Südkorea', 'Corea del Sur', 'Coreia do Sul'),
('Sri Lanka', 3, 'Stato dell\'Asia meridionale.', 'Note su Sri Lanka', 'LK', 'LKA', '144', 'path/to/sri_lanka.png', FALSE, 'Sri Lanka', 'Sri Lanka', 'Sri Lanka', 'Sri Lanka', 'Sri Lanka', 'Sri Lanka'),
('Syria', 3, 'Stato dell\'Asia sud-occidentale.', 'Note su Syria', 'SY', 'SYR', '760', 'path/to/syria.png', FALSE, 'Siria', 'Syria', 'Syrie', 'Syrien', 'Siria', 'Síria'),
('Tajikistan', 3, 'Stato dell\'Asia centrale.', 'Note su Tajikistan', 'TJ', 'TJK', '762', 'path/to/tajikistan.png', FALSE, 'Tagikistan', 'Tajikistan', 'Tadjikistan', 'Tadschikistan', 'Tayikistán', 'Tajiquistão'),
('Thailand', 3, 'Stato dell\'Asia sud-orientale.', 'Note su Thailand', 'TH', 'THA', '764', 'path/to/thailand.png', FALSE, 'Thailandia', 'Thailand', 'Thaïlande', 'Thailand', 'Tailandia', 'Tailândia'),
('Timor-Leste', 3, 'Stato dell\'Asia sud-orientale.', 'Note su Timor-Leste', 'TL', 'TLS', '626', 'path/to/timor_leste.png', FALSE, 'Timor Est', 'Timor-Leste', 'Timor-Oriental', 'Osttimor', 'Timor-Leste', 'Timor-Leste'),
('Turkey', 3, 'Stato dell\'Asia occidentale.', 'Note su Turkey', 'TR', 'TUR', '792', 'path/to/turkey.png', FALSE, 'Turchia', 'Turkey', 'Turquie', 'Türkei', 'Turquía', 'Turquia'),
('Turkmenistan', 3, 'Stato dell\'Asia centrale.', 'Note su Turkmenistan', 'TM', 'TKM', '795', 'path/to/turkmenistan.png', FALSE, 'Turkmenistan', 'Turkmenistan', 'Turkménistan', 'Turkmenistan', 'Turkmenistán', 'Turcomenistão'),
('United Arab Emirates', 3, 'Stato dell\'Asia sud-occidentale.', 'Note su United Arab Emirates', 'AE', 'ARE', '784', 'path/to/united_arab_emirates.png', FALSE, 'Emirati Arabi Uniti', 'United Arab Emirates', 'Émirats Arabes Unis', 'Vereinigte Arabische Emirate', 'Emiratos Árabes Unidos', 'Emirados Árabes Unidos'),
('Uzbekistan', 3, 'Stato dell\'Asia centrale.', 'Note su Uzbekistan', 'UZ', 'UZB', '860', 'path/to/uzbekistan.png', FALSE, 'Uzbekistan', 'Uzbekistan', 'Ouzbékistan', 'Usbekistan', 'Uzbekistán', 'Uzbequistão'),
('Yemen', 3, 'Stato dell\'Asia sud-occidentale.', 'Note su Yemen', 'YE', 'YEM', '887', 'path/to/yemen.png', FALSE, 'Yemen', 'Yemen', 'Yémen', 'Jemen', 'Yemen', 'Iémen');

INSERT INTO lmgc_Countries (name, continent_id, description, notes, iso_alpha_2, iso_alpha_3, iso_numeric, image_path, suspended, name_italian, name_english, name_french, name_german, name_spanish, name_portuguese) VALUES
('Albania', 4, 'Stato dei Balcani.', 'Note su Albania', 'AL', 'ALB', '008', 'path/to/albania.png', FALSE, 'Albania', 'Albania', 'Albanie', 'Albanien', 'Albania', 'Albânia'),
('Andorra', 4, 'Principato situato tra Francia e Spagna.', 'Note su Andorra', 'AD', 'AND', '020', 'path/to/andorra.png', FALSE, 'Andorra', 'Andorra', 'Andorre', 'Andorra', 'Andorra', 'Andorra'),
('Austria', 4, 'Stato dell\'Europa centrale.', 'Note su Austria', 'AT', 'AUT', '040', 'path/to/austria.png', FALSE, 'Austria', 'Austria', 'Autriche', 'Österreich', 'Austria', 'Áustria'),
('Belarus', 4, 'Stato dell\'Europa orientale.', 'Note su Belarus', 'BY', 'BLR', '112', 'path/to/belarus.png', FALSE, 'Bielorussia', 'Belarus', 'Bélarus', 'Weißrussland', 'Bielorrusia', 'Bielorrússia'),
('Belgium', 4, 'Stato dell\'Europa occidentale.', 'Note su Belgium', 'BE', 'BEL', '056', 'path/to/belgium.png', FALSE, 'Belgio', 'Belgium', 'Belgique', 'Belgien', 'Bélgica', 'Bélgica'),
('Bosnia and Herzegovina', 4, 'Stato dei Balcani.', 'Note su Bosnia and Herzegovina', 'BA', 'BIH', '070', 'path/to/bosnia_and_herzegovina.png', FALSE, 'Bosnia ed Erzegovina', 'Bosnia and Herzegovina', 'Bosnie-Herzégovine', 'Bosnien und Herzegowina', 'Bosnia y Herzegovina', 'Bósnia e Herzegovina'),
('Bulgaria', 4, 'Stato dei Balcani.', 'Note su Bulgaria', 'BG', 'BGR', '100', 'path/to/bulgaria.png', FALSE, 'Bulgaria', 'Bulgaria', 'Bulgarie', 'Bulgarien', 'Bulgaria', 'Bulgária'),
('Croatia', 4, 'Stato dei Balcani.', 'Note su Croatia', 'HR', 'HRV', '191', 'path/to/croatia.png', FALSE, 'Croazia', 'Croatia', 'Croatie', 'Kroatien', 'Croacia', 'Croácia'),
('Cyprus', 4, 'Isola nel Mediterraneo orientale.', 'Note su Cyprus', 'CY', 'CYP', '196', 'path/to/cyprus.png', FALSE, 'Cipro', 'Cyprus', 'Chypre', 'Zypern', 'Chipre', 'Chipre'),
('Czech Republic', 4, 'Stato dell\'Europa centrale.', 'Note su Czech Republic', 'CZ', 'CZE', '203', 'path/to/czech_republic.png', FALSE, 'Repubblica Ceca', 'Czech Republic', 'République Tchèque', 'Tschechien', 'República Checa', 'República Checa'),
('Denmark', 4, 'Stato dell\'Europa settentrionale.', 'Note su Denmark', 'DK', 'DNK', '208', 'path/to/denmark.png', FALSE, 'Danimarca', 'Denmark', 'Danemark', 'Dänemark', 'Dinamarca', 'Dinamarca'),
('Estonia', 4, 'Stato dell\'Europa settentrionale.', 'Note su Estonia', 'EE', 'EST', '233', 'path/to/estonia.png', FALSE, 'Estonia', 'Estonia', 'Estonie', 'Estland', 'Estonia', 'Estônia'),
('Finland', 4, 'Stato dell\'Europa settentrionale.', 'Note su Finland', 'FI', 'FIN', '246', 'path/to/finland.png', FALSE, 'Finlandia', 'Finland', 'Finlande', 'Finnland', 'Finlandia', 'Finlândia'),
('France', 4, 'Stato dell\'Europa occidentale.', 'Note su France', 'FR', 'FRA', '250', 'path/to/france.png', FALSE, 'Francia', 'France', 'France', 'Frankreich', 'Francia', 'França'),
('Germany', 4, 'Stato dell\'Europa centrale.', 'Note su Germany', 'DE', 'DEU', '276', 'path/to/germany.png', FALSE, 'Germania', 'Germany', 'Allemagne', 'Deutschland', 'Alemania', 'Alemanha'),
('Greece', 4, 'Stato dei Balcani.', 'Note su Greece', 'GR', 'GRC', '300', 'path/to/greece.png', FALSE, 'Grecia', 'Greece', 'Grèce', 'Griechenland', 'Grecia', 'Grécia'),
('Hungary', 4, 'Stato dell\'Europa centrale.', 'Note su Hungary', 'HU', 'HUN', '348', 'path/to/hungary.png', FALSE, 'Ungheria', 'Hungary', 'Hongrie', 'Ungarn', 'Hungría', 'Hungria'),
('Iceland', 4, 'Isola dell\'Europa settentrionale.', 'Note su Iceland', 'IS', 'ISL', '352', 'path/to/iceland.png', FALSE, 'Islanda', 'Iceland', 'Islande', 'Island', 'Islandia', 'Islândia'),
('Ireland', 4, 'Stato dell\'Europa occidentale.', 'Note su Ireland', 'IE', 'IRL', '372', 'path/to/ireland.png', FALSE, 'Irlanda', 'Ireland', 'Irlande', 'Irland', 'Irlanda', 'Irlanda'),
('Italy', 4, 'Stato dell\'Europa meridionale.', 'Note su Italy', 'IT', 'ITA', '380', 'path/to/italy.png', FALSE, 'Italia', 'Italy', 'Italie', 'Italien', 'Italia', 'Itália'),
('Kosovo', 4, 'Stato dell\'Europa sud-orientale.', 'Note su Kosovo', 'XK', 'XKX', '999', 'path/to/kosovo.png', FALSE, 'Kosovo', 'Kosovo', 'Kosovo', 'Kosovo', 'Kosovo', 'Kosovo'),
('Latvia', 4, 'Stato dell\'Europa settentrionale.', 'Note su Latvia', 'LV', 'LVA', '428', 'path/to/latvia.png', FALSE, 'Lettonia', 'Latvia', 'Lettonie', 'Lettland', 'Letonia', 'Letônia'),
('Liechtenstein', 4, 'Principato situato tra Svizzera e Austria.', 'Note su Liechtenstein', 'LI', 'LIE', '438', 'path/to/liechtenstein.png', FALSE, 'Liechtenstein', 'Liechtenstein', 'Liechtenstein', 'Liechtenstein', 'Liechtenstein', 'Liechtenstein'),
('Lithuania', 4, 'Stato dell\'Europa orientale.', 'Note su Lithuania', 'LT', 'LTU', '440', 'path/to/lithuania.png', FALSE, 'Lituania', 'Lithuania', 'Lituanie', 'Litauen', 'Lituania', 'Lituânia'),
('Luxembourg', 4, 'Stato dell\'Europa occidentale.', 'Note su Luxembourg', 'LU', 'LUX', '442', 'path/to/luxembourg.png', FALSE, 'Lussemburgo', 'Luxembourg', 'Luxembourg', 'Luxemburg', 'Luxemburgo', 'Luxemburgo'),
('Malta', 4, 'Isola nel Mediterraneo centrale.', 'Note su Malta', 'MT', 'MLT', '470', 'path/to/malta.png', FALSE, 'Malta', 'Malta', 'Malte', 'Malta', 'Malta', 'Malta'),
('Moldova', 4, 'Stato dell\'Europa orientale.', 'Note su Moldova', 'MD', 'MDA', '498', 'path/to/moldova.png', FALSE, 'Moldova', 'Moldova', 'Moldova', 'Moldawien', 'Moldova', 'Moldova'),
('Monaco', 4, 'Principato situato sulla Riviera francese.', 'Note su Monaco', 'MC', 'MCO', '492', 'path/to/monaco.png', FALSE, 'Monaco', 'Monaco', 'Monaco', 'Monaco', 'Mónaco', 'Mônaco'),
('Montenegro', 4, 'Stato dei Balcani.', 'Note su Montenegro', 'ME', 'MNE', '499', 'path/to/montenegro.png', FALSE, 'Montenegro', 'Montenegro', 'Monténégro', 'Montenegro', 'Montenegro', 'Montenegro'),
('Netherlands', 4, 'Stato dell\'Europa occidentale.', 'Note su Netherlands', 'NL', 'NLD', '528', 'path/to/netherlands.png', FALSE, 'Paesi Bassi', 'Netherlands', 'Pays-Bas', 'Niederlande', 'Países Bajos', 'Países Baixos'),
('North Macedonia', 4, 'Stato dei Balcani.', 'Note su North Macedonia', 'MK', 'MKD', '807', 'path/to/north_macedonia.png', FALSE, 'Macedonia del Nord', 'North Macedonia', 'Macédoine du Nord', 'Nordmazedonien', 'Macedonia del Norte', 'Macedônia do Norte'),
('Norway', 4, 'Stato dell\'Europa settentrionale.', 'Note su Norway', 'NO', 'NOR', '578', 'path/to/norway.png', FALSE, 'Norvegia', 'Norway', 'Norvège', 'Norwegen', 'Noruega', 'Noruega'),
('Poland', 4, 'Stato dell\'Europa centrale.', 'Note su Poland', 'PL', 'POL', '616', 'path/to/poland.png', FALSE, 'Polonia', 'Poland', 'Pologne', 'Polen', 'Polonia', 'Polônia'),
('Portugal', 4, 'Stato dell\'Europa sud-occidentale.', 'Note su Portugal', 'PT', 'PRT', '620', 'path/to/portugal.png', FALSE, 'Portogallo', 'Portugal', 'Portugal', 'Portugal', 'Portugal', 'Portugal'),
('Romania', 4, 'Stato dei Balcani.', 'Note su Romania', 'RO', 'ROU', '642', 'path/to/romania.png', FALSE, 'Romania', 'Romania', 'Roumanie', 'Rumänien', 'Rumanía', 'Romênia'),
('Russia', 4, 'Stato dell\'Europa orientale.', 'Note su Russia', 'RU', 'RUS', '643', 'path/to/russia.png', FALSE, 'Russia', 'Russia', 'Russie', 'Russland', 'Rusia', 'Rússia'),
('San Marino', 4, 'Stato situato all\'interno dell\'Italia.', 'Note su San Marino', 'SM', 'SMR', '674', 'path/to/san_marino.png', FALSE, 'San Marino', 'San Marino', 'Saint-Marin', 'San Marino', 'San Marino', 'San Marino'),
('Serbia', 4, 'Stato dei Balcani.', 'Note su Serbia', 'RS', 'SRB', '688', 'path/to/serbia.png', FALSE, 'Serbia', 'Serbia', 'Serbie', 'Serbien', 'Serbia', 'Sérvia'),
('Slovakia', 4, 'Stato dell\'Europa centrale.', 'Note su Slovakia', 'SK', 'SVK', '703', 'path/to/slovakia.png', FALSE, 'Slovacchia', 'Slovakia', 'Slovaquie', 'Slowakei', 'Eslovaquia', 'Eslováquia'),
('Slovenia', 4, 'Stato dei Balcani.', 'Note su Slovenia', 'SI', 'SVN', '705', 'path/to/slovenia.png', FALSE, 'Slovenia', 'Slovenia', 'Slovénie', 'Slowenien', 'Eslovenia', 'Eslovênia'),
('Spain', 4, 'Stato dell\'Europa sud-occidentale.', 'Note su Spain', 'ES', 'ESP', '724', 'path/to/spain.png', FALSE, 'Spagna', 'Spain', 'Espagne', 'Spanien', 'España', 'Espanha'),
('Sweden', 4, 'Stato dell\'Europa settentrionale.', 'Note su Sweden', 'SE', 'SWE', '752', 'path/to/sweden.png', FALSE, 'Svezia', 'Sweden', 'Suède', 'Schweden', 'Suecia', 'Suécia'),
('Switzerland', 4, 'Stato dell\'Europa centrale.', 'Note su Switzerland', 'CH', 'CHE', '756', 'path/to/switzerland.png', FALSE, 'Svizzera', 'Switzerland', 'Suisse', 'Schweiz', 'Suiza', 'Suíça'),
('Turkey', 4, 'Stato dell\'Europa sud-orientale.', 'Note su Turkey', 'TR', 'TUR', '792', 'path/to/turkey.png', FALSE, 'Turchia', 'Turkey', 'Turquie', 'Türkei', 'Turquía', 'Turquia'),
('Ukraine', 4, 'Stato dell\'Europa orientale.', 'Note su Ukraine', 'UA', 'UKR', '804', 'path/to/ukraine.png', FALSE, 'Ucraina', 'Ukraine', 'Ukraine', 'Ukraine', 'Ucrania', 'Ucrânia'),
('United Kingdom', 4, 'Stato dell\'Europa occidentale.', 'Note su United Kingdom', 'GB', 'GBR', '826', 'path/to/united_kingdom.png', FALSE, 'Regno Unito', 'United Kingdom', 'Royaume-Uni', 'Vereinigtes Königreich', 'Reino Unido', 'Reino Unido'),
('Vatican City', 4, 'Stato situato all\'interno di Roma.', 'Note su Vatican City', 'VA', 'VAT', '336', 'path/to/vatican_city.png', FALSE, 'Città del Vaticano', 'Vatican City', 'Vatican', 'Vatikanstadt', 'Ciudad del Vaticano', 'Cidade do Vaticano');

INSERT INTO lmgc_Countries (name, continent_id, description, notes, iso_alpha_2, iso_alpha_3, iso_numeric, image_path, suspended, name_italian, name_english, name_french, name_german, name_spanish, name_portuguese) VALUES
('Australia', 5, 'Stato dell\'Oceania.', 'Note su Australia', 'AU', 'AUS', '036', 'path/to/australia.png', FALSE, 'Australia', 'Australia', 'Australie', 'Australien', 'Australia', 'Austrália'),
('Fiji', 5, 'Stato dell\'Oceania.', 'Note su Fiji', 'FJ', 'FJI', '242', 'path/to/fiji.png', FALSE, 'Figi', 'Fiji', 'Fidji', 'Fidschi', 'Fiyi', 'Fiji'),
('Kiribati', 5, 'Stato dell\'Oceania.', 'Note su Kiribati', 'KI', 'KIR', '296', 'path/to/kiribati.png', FALSE, 'Kiribati', 'Kiribati', 'Kiribati', 'Kiribati', 'Kiribati', 'Kiribati'),
('Marshall Islands', 5, 'Stato dell\'Oceania.', 'Note su Marshall Islands', 'MH', 'MHL', '584', 'path/to/marshall_islands.png', FALSE, 'Isole Marshall', 'Marshall Islands', 'Îles Marshall', 'Marshallinseln', 'Islas Marshall', 'Ilhas Marshall'),
('Micronesia', 5, 'Stato dell\'Oceania.', 'Note su Micronesia', 'FM', 'FSM', '583', 'path/to/micronesia.png', FALSE, 'Micronesia', 'Micronesia', 'Micronésie', 'Mikronesien', 'Micronesia', 'Micronésia'),
('Nauru', 5, 'Stato dell\'Oceania.', 'Note su Nauru', 'NR', 'NRU', '520', 'path/to/nauru.png', FALSE, 'Nauru', 'Nauru', 'Nauru', 'Nauru', 'Nauru', 'Nauru'),
('New Zealand', 5, 'Stato dell\'Oceania.', 'Note su New Zealand', 'NZ', 'NZL', '554', 'path/to/new_zealand.png', FALSE, 'Nuova Zelanda', 'New Zealand', 'Nouvelle-Zélande', 'Neuseeland', 'Nueva Zelanda', 'Nova Zelândia'),
('Palau', 5, 'Stato dell\'Oceania.', 'Note su Palau', 'PW', 'PLW', '585', 'path/to/palau.png', FALSE, 'Palau', 'Palau', 'Palaos', 'Palau', 'Palaos', 'Palau'),
('Papua New Guinea', 5, 'Stato dell\'Oceania.', 'Note su Papua New Guinea', 'PG', 'PNG', '598', 'path/to/papua_new_guinea.png', FALSE, 'Papua Nuova Guinea', 'Papua New Guinea', 'Papouasie-Nouvelle-Guinée', 'Papua-Neuguinea', 'Papúa Nueva Guinea', 'Papua-Nova Guiné'),
('Samoa', 5, 'Stato dell\'Oceania.', 'Note su Samoa', 'WS', 'WSM', '882', 'path/to/samoa.png', FALSE, 'Samoa', 'Samoa', 'Samoa', 'Samoa', 'Samoa', 'Samoa'),
('Solomon Islands', 5, 'Stato dell\'Oceania.', 'Note su Solomon Islands', 'SB', 'SLB', '090', 'path/to/solomon_islands.png', FALSE, 'Isole Solomon', 'Solomon Islands', 'Îles Salomon', 'Salomonen', 'Islas Salomón', 'Ilhas Salomão'),
('Tonga', 5, 'Stato dell\'Oceania.', 'Note su Tonga', 'TO', 'TON', '776', 'path/to/tonga.png', FALSE, 'Tonga', 'Tonga', 'Tonga', 'Tonga', 'Tonga', 'Tonga'),
('Tuvalu', 5, 'Stato dell\'Oceania.', 'Note su Tuvalu', 'TV', 'TUV', '798', 'path/to/tuvalu.png', FALSE, 'Tuvalu', 'Tuvalu', 'Tuvalu', 'Tuvalu', 'Tuvalu', 'Tuvalu'),
('Vanuatu', 5, 'Stato dell\'Oceania.', 'Note su Vanuatu', 'VU', 'VUT', '548', 'path/to/vanuatu.png', FALSE, 'Vanuatu', 'Vanuatu', 'Vanuatu', 'Vanuatu', 'Vanuatu', 'Vanuatu');
