include:
  - local: '/ci-templates/syntax-checks.yml'
  - local: '/ci-templates/validation-checks.yml'
  - local: '/ci-templates/version-checks.yml'
  - local: '/ci-templates/test-checks.yml'

stages:
  - syntax
  - validation
  - version
  - test
