stages:
  - documentation
  - formatting
  - validation
  - testing
  - deploy

variables:
  EXCLUDED_PATHS: |
    node_modules/**/*
    vendor/**/*
    logs/**/*
    tests/**/*
    tmp/**/*

include:
  - local: 'ci/documentation/php-doc.yml'
  - local: 'ci/documentation/js-doc.yml'
  - local: 'ci/formatting/php-format.yml'
  - local: 'ci/formatting/html-format.yml'
  - local: 'ci/formatting/css-format.yml'
  - local: 'ci/formatting/js-format.yml'
  - local: 'ci/formatting/sql-format.yml'
  - local: 'ci/validation/php-validation.yml'
  - local: 'ci/validation/html-validation.yml'
  - local: 'ci/validation/css-validation.yml'
  - local: 'ci/validation/js-validation.yml'
  - local: 'ci/validation/sql-validation.yml'
  - local: 'ci/tests/php-8.0-test.yml'
  - local: 'ci/tests/php-8.1-test.yml'
  - local: 'ci/tests/php-8.2-test.yml'
  - local: 'ci/tests/php-8.3-test.yml'
  - local: 'ci/tests/functional-test.yml'
