CREATE TABLE IF NOT EXISTS lm_Genders (
    id INT AUTO_INCREMENT PRIMARY KEY,
    gender VARCHAR(50) NOT NULL UNIQUE,
    notes VARCHAR(255),
    creation_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

INSERT INTO lm_Genders (gender) VALUES
('Maschio'),
('Femmina'),
('Altro');
