CREATE TABLE IF NOT EXISTS lmgc_IndustrySectors (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    notes VARCHAR(255),
    creation_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

ALTER TABLE lmgc_IndustrySectors
ADD COLUMN name_en VARCHAR(255) NULL,  -- Inglese
ADD COLUMN name_it VARCHAR(255) NULL,  -- Italiano
ADD COLUMN name_fr VARCHAR(255) NULL,  -- Francese
ADD COLUMN name_es VARCHAR(255) NULL,  -- Spagnolo
ADD COLUMN name_de VARCHAR(255) NULL;  -- Tedesco

INSERT INTO lmgc_IndustrySectors (name, name_en, name_it, name_fr, name_es, name_de) VALUES
('Home Appliances', 'Home Appliances', 'Elettrodomestici', 'Appareils ménagers', 'Electrodomésticos', 'Haushaltsgeräte'),
('Furniture', 'Furniture', 'Mobili', 'Meubles', 'Muebles', 'Möbel'),
('Garden Tools', 'Garden Tools', 'Attrezzi da Giardino', 'Outils de jardin', 'Herramientas de jardín', 'Gartengeräte'),
('Automotive Parts', 'Automotive Parts', 'Parti Automobilistiche', 'Pièces automobiles', 'Piezas de automóviles', 'Autoteile'),
('Cleaning Supplies', 'Cleaning Supplies', 'Forniture per Pulizia', 'Produits de nettoyage', 'Productos de limpieza', 'Reinigungsmittel'),
('Outdoor Furniture', 'Outdoor Furniture', 'Arredamento da Esterno', 'Mobilier extérieur', 'Muebles de exterior', 'Gartenmöbel'),
('Kitchenware', 'Kitchenware', 'Utensili da Cucina', 'Ustensiles de cuisine', 'Utensilios de cocina', 'Küchenutensilien'),
('Gardening Equipment', 'Gardening Equipment', 'Attrezzature da Giardinaggio', 'Équipements de jardinage', 'Equipo de jardinería', 'Gartenwerkzeuge'),
('Automotive Accessories', 'Automotive Accessories', 'Accessori per Auto', 'Accessoires automobiles', 'Accesorios para automóviles', 'Autozubehör'),
('Home Improvement', 'Home Improvement', 'Ristrutturazione Casa', 'Amélioration de l\'habitat', 'Mejora del hogar', 'Hausrenovierung'),
('Bedding', 'Bedding', 'Biancheria da Letto', 'Literie', 'Ropa de cama', 'Bettwäsche'),
('Storage Solutions', 'Storage Solutions', 'Soluzioni per lo Stoccaggio', 'Solutions de stockage', 'Soluciones de almacenamiento', 'Lösungen zur Aufbewahrung'),
('Decorative Items', 'Decorative Items', 'Articoli Decorativi', 'Articles décoratifs', 'Artículos decorativos', 'Dekorationsartikel'),
('DIY Tools', 'DIY Tools', 'Attrezzi Fai-da-Te', 'Outils de bricolage', 'Herramientas de bricolaje', 'Werkzeuge zum Selbermachen'),
('Electrical Appliances', 'Electrical Appliances', 'Elettrodomestici', 'Appareils électriques', 'Electrodomésticos eléctricos', 'Elektrische Geräte'),
('Car Care', 'Car Care', 'Cura dell\'Auto', 'Entretien automobile', 'Cuidado del coche', 'Autopflege'),
('Heating Systems', 'Heating Systems', 'Sistemi di Riscaldamento', 'Systèmes de chauffage', 'Sistemas de calefacción', 'Heizsysteme'),
('Cooling Systems', 'Cooling Systems', 'Sistemi di Raffreddamento', 'Systèmes de refroidissement', 'Sistemas de refrigeración', 'Kühlsysteme'),
('Safety Equipment', 'Safety Equipment', 'Equipaggiamento di Sicurezza', 'Équipement de sécurité', 'Equipo de seguridad', 'Sicherheitsausrüstung'),
('Kitchen Appliances', 'Kitchen Appliances', 'Elettrodomestici da Cucina', 'Appareils de cuisine', 'Electrodomésticos de cocina', 'Küchengeräte'),
('Furniture Accessories', 'Furniture Accessories', 'Accessori per Mobili', 'Accessoires de meubles', 'Accesorios de muebles', 'Möbelzubehör'),
('Plumbing Supplies', 'Plumbing Supplies', 'Forniture Idrauliche', 'Fournitures de plomberie', 'Suministros de fontanería', 'Sanitärbedarf'),
('Home Security', 'Home Security', 'Sicurezza Domestica', 'Sécurité domestique', 'Seguridad en el hogar', 'Haussicherheit'),
('Outdoor Equipment', 'Outdoor Equipment', 'Attrezzatura da Esterno', 'Équipement extérieur', 'Equipo exterior', 'Outdoor-Ausrüstung'),
('Automotive Maintenance', 'Automotive Maintenance', 'Manutenzione Auto', 'Entretien automobile', 'Mantenimiento de automóviles', 'Automobilwartung'),
('Home Organization', 'Home Organization', 'Organizzazione della Casa', 'Organisation de la maison', 'Organización del hogar', 'Hausorganisation'),
('Gardening Supplies', 'Gardening Supplies', 'Forniture da Giardinaggio', 'Fournitures de jardinage', 'Suministros de jardinería', 'Gartenbedarf'),
('Fitness Equipment', 'Fitness Equipment', 'Attrezzatura per Fitness', 'Équipement de fitness', 'Equipo de fitness', 'Fitnessgeräte'),
('Pet Supplies', 'Pet Supplies', 'Forniture per Animali', 'Fournitures pour animaux', 'Suministros para mascotas', 'Haustierbedarf'),
('Home Entertainment', 'Home Entertainment', 'Intrattenimento per la Casa', 'Divertissement à domicile', 'Entretenimiento en el hogar', 'Hausunterhaltung'),
('Cooking Appliances', 'Cooking Appliances', 'Elettrodomestici da Cucina', 'Appareils de cuisson', 'Electrodomésticos de cocina', 'Kochgeräte'),
('Bathroom Fixtures', 'Bathroom Fixtures', 'Accessori per il Bagno', 'Accessoires de salle de bain', 'Accesorios de baño', 'Badezimmerausstattung'),
('Lighting Solutions', 'Lighting Solutions', 'Soluzioni di Illuminazione', 'Solutions d\'éclairage', 'Soluciones de iluminación', 'Beleuchtungslösungen'),
('Furniture Repair', 'Furniture Repair', 'Riparazione Mobili', 'Réparation de meubles', 'Reparación de muebles', 'Möbelreparatur'),
('Automotive Electronics', 'Automotive Electronics', 'Elettronica per Auto', 'Électronique automobile', 'Electrónica para automóviles', 'Automobilelektronik'),
('Garden Furniture', 'Garden Furniture', 'Arredamento da Giardino', 'Mobilier de jardin', 'Muebles de jardín', 'Gartenmöbel'),
('Household Chemicals', 'Household Chemicals', 'Chimica Domestica', 'Produits chimiques pour la maison', 'Productos químicos para el hogar', 'Haushaltschemikalien'),
('Power Tools', 'Power Tools', 'Utensili Elettrici', 'Outils électriques', 'Herramientas eléctricas', 'Elektrowerkzeuge'),
('Office Furniture', 'Office Furniture', 'Mobili per Ufficio', 'Mobilier de bureau', 'Muebles de oficina', 'Büromöbel'),
('Cleaning Tools', 'Cleaning Tools', 'Attrezzi per Pulizia', 'Outils de nettoyage', 'Herramientas de limpieza', 'Reinigungswerkzeuge'),
('Home Decor', 'Home Decor', 'Decorazioni per la Casa', 'Décoration intérieure', 'Decoración del hogar', 'Heimdekoration'),
('Garden Lighting', 'Garden Lighting', 'Illuminazione da Giardino', 'Éclairage de jardin', 'Iluminación de jardín', 'Gartenbeleuchtung'),
('Outdoor Sports Equipment', 'Outdoor Sports Equipment', 'Attrezzatura Sportiva da Esterno', 'Équipement de sport extérieur', 'Equipo deportivo exterior', 'Outdoor-Sportausrüstung'),
('Storage Containers', 'Storage Containers', 'Contenitori per Stoccaggio', 'Conteneurs de stockage', 'Contenedores de almacenamiento', 'Lagerbehälter'),
('Hygiene Products', 'Hygiene Products', 'Prodotti per l\'Igiene', 'Produits d\'hygiène', 'Productos de higiene', 'Hygieneprodukte'),
('Automotive Tools', 'Automotive Tools', 'Attrezzi per Auto', 'Outils pour automobile', 'Herramientas para automóviles', 'Automobilwerkzeuge'),
('Interior Design', 'Interior Design', 'Design d\'Interni', 'Design d\'intérieur', 'Diseño de interiores', 'Innenarchitektur'),
('Outdoor Structures', 'Outdoor Structures', 'Strutture da Esterno', 'Structures extérieures', 'Estructuras exteriores', 'Außenstrukturen'),
('Maintenance Supplies', 'Maintenance Supplies', 'Materiali per Manutenzione', 'Fournitures de maintenance', 'Suministros de mantenimiento', 'Wartungsbedarf'),
('Energy Efficiency Products', 'Energy Efficiency Products', 'Prodotti per l\'Efficienza Energetica', 'Produits d\'efficacité énergétique', 'Productos de eficiencia energética', 'Energieeffizienzprodukte'),
('Smart Home Devices', 'Smart Home Devices', 'Dispositivi per Casa Intelligente', 'Appareils de maison intelligente', 'Dispositivos para el hogar inteligente', 'Smart-Home-Geräte'),
('Garden Irrigation', 'Garden Irrigation', 'Irrigazione del Giardino', 'Irrigation du jardin', 'Irrigación del jardín', 'Gartenbewässerung'),
('Home Improvement Tools', 'Home Improvement Tools', 'Strumenti per Ristrutturazione Casa', 'Outils d\'amélioration de l\'habitat', 'Herramientas para la mejora del hogar', 'Renovierungswerkzeuge'),
('Automotive Safety', 'Automotive Safety', 'Sicurezza Auto', 'Sécurité automobile', 'Seguridad del automóvil', 'Automobilsicherheit'),
('Garden Pests Control', 'Garden Pests Control', 'Controllo dei Parassiti da Giardino', 'Contrôle des parasites de jardin', 'Control de plagas del jardín', 'Schädlingsbekämpfung im Garten'),
('Heating & Cooling', 'Heating & Cooling', 'Riscaldamento e Raffreddamento', 'Chauffage et refroidissement', 'Calefacción y refrigeración', 'Heizung & Kühlung'),
('Luxury Furniture', 'Luxury Furniture', 'Mobili di Lusso', 'Meubles de luxe', 'Muebles de lujo', 'Luxusmöbel'),
('Car Accessories', 'Car Accessories', 'Accessori per Auto', 'Accessoires pour voiture', 'Accesorios para automóviles', 'Autozubehör'),
('Outdoor Cooking', 'Outdoor Cooking', 'Cucina da Esterno', 'Cuisine extérieure', 'Cocina al aire libre', 'Outdoor-Kochen'),
('Home Renovation', 'Home Renovation', 'Ristrutturazione della Casa', 'Rénovation de maison', 'Renovación del hogar', 'Hausrenovierung'),
('Automotive Care Products', 'Automotive Care Products', 'Prodotti per Cura Auto', 'Produits d\'entretien automobile', 'Productos para el cuidado del automóvil', 'Autopflegeprodukte'),
('Garden Fertilizers', 'Garden Fertilizers', 'Fertilizzanti per Giardino', 'Engrais pour jardin', 'Fertilizantes para jardín', 'Gartenkompost'),
('Home Textiles', 'Home Textiles', 'Tessili per la Casa', 'Textiles pour la maison', 'Textiles para el hogar', 'Hausstoffe'),
('Interior Lighting', 'Interior Lighting', 'Illuminazione per Interni', 'Éclairage intérieur', 'Iluminación interior', 'Innenbeleuchtung'),
('Garden Water Features', 'Garden Water Features', 'Elementi Acquatici per Giardino', 'Éléments aquatiques de jardin', 'Características acuáticas de jardín', 'Garten-Wasseranlagen'),
('Home Office Supplies', 'Home Office Supplies', 'Forniture per Ufficio in Casa', 'Fournitures pour bureau à domicile', 'Suministros para oficina en casa', 'Bürobedarf für Zuhause'),
('Automotive Fluids', 'Automotive Fluids', 'Fluidi per Auto', 'Fluides automobiles', 'Fluidos para automóviles', 'Auto-Flüssigkeiten'),
('Outdoor Seating', 'Outdoor Seating', 'Posti a Sedere da Esterno', 'Sièges d\'extérieur', 'Asientos exteriores', 'Außensitzplätze'),
('Home Cleaning Products', 'Home Cleaning Products', 'Prodotti per Pulizia della Casa', 'Produits de nettoyage pour la maison', 'Productos de limpieza para el hogar', 'Hausreinigungsprodukte'),
('Garden Soil', 'Garden Soil', 'Terra per Giardino', 'Terre de jardin', 'Suelo para jardín', 'Gartenerde'),
('Kitchen Storage', 'Kitchen Storage', 'Stoccaggio per Cucina', 'Rangement de cuisine', 'Almacenamiento de cocina', 'Küchenlagerung'),
('Automotive Battery', 'Automotive Battery', 'Batteria per Auto', 'Batterie automobile', 'Batería de automóvil', 'Autobatterie'),
('Pet Care Products', 'Pet Care Products', 'Prodotti per Cura Animali', 'Produits de soins pour animaux', 'Productos para el cuidado de mascotas', 'Haustierpflegeprodukte'),
('Seasonal Decor', 'Seasonal Decor', 'Decorazioni Stagionali', 'Décor saisonnier', 'Decoraciones estacionales', 'Saisonale Dekoration'),
('Home Comfort', 'Home Comfort', 'Comfort per la Casa', 'Confort domestique', 'Comodidad en el hogar', 'Hauskomfort'),
('Garden Seeds', 'Garden Seeds', 'Semi per Giardino', 'Graines de jardin', 'Semillas para jardín', 'Gartenpflanzen'),
('Automotive Tires', 'Automotive Tires', 'Pneumatici per Auto', 'Pneus automobiles', 'Neumáticos para automóviles', 'Autoreifen'),
('Home Maintenance', 'Home Maintenance', 'Manutenzione della Casa', 'Entretien de la maison', 'Mantenimiento del hogar', 'Hauswartung'),
('Garden Tools Accessories', 'Garden Tools Accessories', 'Accessori per Attrezzi da Giardinaggio', 'Accessoires pour outils de jardin', 'Accesorios para herramientas de jardín', 'Gartengeräte Zubehör'),
('Storage Furniture', 'Storage Furniture', 'Mobili per Stoccaggio', 'Mobilier de rangement', 'Muebles de almacenamiento', 'Lager Möbel'),
('Automotive Repair Tools', 'Automotive Repair Tools', 'Attrezzi per Riparazioni Auto', 'Outils de réparation automobile', 'Herramientas de reparación de automóviles', 'Automobilreparaturwerkzeuge'),
('Home Health Products', 'Home Health Products', 'Prodotti per la Salute della Casa', 'Produits de santé pour la maison', 'Productos de salud para el hogar', 'Hausgesundheitsprodukte'),
('Garden Pest Control', 'Garden Pest Control', 'Controllo dei Parassiti del Giardino', 'Contrôle des parasites de jardin', 'Control de plagas en el jardín', 'Schädlingsbekämpfung im Garten'),
('Furniture Care', 'Furniture Care', 'Cura dei Mobili', 'Entretien des meubles', 'Cuidado de los muebles', 'Möbelpflege'),
('Automotive Exhaust Systems', 'Automotive Exhaust Systems', 'Sistemi di Scarico per Auto', 'Systèmes d\'échappement automobile', 'Sistemas de escape para automóviles', 'Abgasanlagen'),
('Home Energy Solutions', 'Home Energy Solutions', 'Soluzioni Energetiche per la Casa', 'Solutions énergétiques pour la maison', 'Soluciones energéticas para el hogar', 'Energie Lösungen für Zuhause'),
('Garden Maintenance Tools', 'Garden Maintenance Tools', 'Attrezzi per Manutenzione del Giardino', 'Outils de maintenance de jardin', 'Herramientas de mantenimiento de jardines', 'Gartenpflegewerkzeuge'),
('Home Appliance Parts', 'Home Appliance Parts', 'Parti per Elettrodomestici', 'Pièces d\'appareils électroménagers', 'Piezas de electrodomésticos', 'Haushaltsgeräte Teile'),
('Automotive Glass', 'Automotive Glass', 'Vetri per Auto', 'Verre automobile', 'Vidrios para automóviles', 'Autoglas'),
('Garden Pots', 'Garden Pots', 'Vasi per Giardino', 'Pots de jardin', 'Macetas para jardín', 'Garten Töpfe'),
('Indoor Furniture', 'Indoor Furniture', 'Mobili per Interni', 'Mobilier d\'intérieur', 'Muebles de interior', 'Innenmöbel'),
('Automotive Warranties', 'Automotive Warranties', 'Garanzie per Auto', 'Garanties automobiles', 'Garantías para automóviles', 'Automobilgarantien'),
('Home Renovation Tools', 'Home Renovation Tools', 'Strumenti per Ristrutturazione della Casa', 'Outils de rénovation de maison', 'Herramientas para renovación del hogar', 'Renovierungswerkzeuge'),
('Garden Mulch', 'Garden Mulch', 'Pacciamatura per Giardino', 'Paillis pour jardin', 'Acolchado para jardín', 'Gartenmulch'),
('Furniture Assembly Tools', 'Furniture Assembly Tools', 'Attrezzi per Montaggio Mobili', 'Outils de montage de meubles', 'Herramientas para ensamblaje de muebles', 'Möbelmontagewerkzeuge'),
('Automotive Detailing', 'Automotive Detailing', 'Dettagli per Auto', 'Détaillage automobile', 'Detalles para automóviles', 'Autopflege'),
('Home Cleaning Equipment', 'Home Cleaning Equipment', 'Attrezzatura per Pulizia della Casa', 'Équipement de nettoyage pour la maison', 'Equipo de limpieza para el hogar', 'Hausreinigungsgeräte'),
('Garden Sprayers', 'Garden Sprayers', 'Spruzzatori per Giardino', 'Pulvérisateurs de jardin', 'Pulverizadores de jardín', 'Garten Sprühgeräte'),
('Automotive Care Kits', 'Automotive Care Kits', 'Kit di Cura per Auto', 'Kits de soins automobiles', 'Kits de cuidado para automóviles', 'Auto-Pflegekits'),
('Indoor Plants', 'Indoor Plants', 'Piante da Interno', 'Plantes d\'intérieur', 'Plantas de interior', 'Zimmerpflanzen'),
('Garden Planters', 'Garden Planters', 'Vasi da Giardino', 'Bacs à jardin', 'Macetas de jardín', 'Gartenpflanzgefäße'),
('Automotive Electronics Accessories', 'Automotive Electronics Accessories', 'Accessori per Elettronica Auto', 'Accessoires pour électronique automobile', 'Accesorios para electrónica de automóviles', 'Automobile Elektronik Zubehör'),
('Home Insulation', 'Home Insulation', 'Isolamento per la Casa', 'Isolation pour la maison', 'Aislamiento para el hogar', 'Hausisolierung');
