CREATE TABLE IF NOT EXISTS lm_People (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    surname VARCHAR(255) NOT NULL,
    age INT NOT NULL,
    birthdate DATE NOT NULL,
    city_id INT NULL,
    country_id INT NULL,
    nationality_id INT NULL,
    description VARCHAR(255) NULL,
    user_id INT NOT NULL,
    create_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

ALTER TABLE lm_People
ADD COLUMN email VARCHAR(255);

ALTER TABLE lm_People
ADD CONSTRAINT UC_Email UNIQUE (email);
