name: CSS Analysis

on: [push, pull_request]

jobs:
  css-analysis:
    name: Validate CSS Files
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Stylelint
      run: npm install stylelint stylelint-config-standard

    - name: Run Stylelint
      run: npx stylelint "**/*.css"
