name: JS Analysis

on: [push, pull_request]

jobs:
  js-analysis:
    name: Analyze JS Code
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install ESLint
      run: npm install eslint

    - name: Run ESLint
      run: npx eslint "**/*.js"
