name: JS, HTML, CSS Formatting

on: [push, pull_request]

jobs:
  formatting:
    name: Check JS, HTML, CSS Formatting
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Prettier
      run: npm install prettier

    - name: Run Prettier
      run: npx prettier --check "**/*.{js,html,css}"
