name: JS Unit Tests

on: [push, pull_request]

jobs:
  js-unit-tests:
    name: Run JS Unit Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Dependencies
      run: npm install

    - name: Run Tests
      run: npm test
