name: PHP Analysis

on: [push, pull_request]

jobs:
  php-analysis:
    name: Analyze PHP Code
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install PHPStan
      run: composer global require phpstan/phpstan

    - name: Run PHPStan
      run: phpstan analyse --level max src/
