name: PHP Security Audit

on: [push, pull_request]

jobs:
  php-security-audit:
    name: Run PHP Security Audit
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Security Checker
      run: composer global require enlightn/security-checker

    - name: Run Security Check
      run: security-checker security:check
