DROP TABLE lmgc_Countries;

CREATE TABLE IF NOT EXISTS lmgc_Countries (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    continent_id INT NOT NULL,
    creationDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updateDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (continent_id) REFERENCES lmgc_Continents(id)
);

ALTER TABLE lmgc_Countries
ADD COLUMN nota TEXT NULL,
ADD COLUMN name_en VARCHAR(255) NULL,
ADD COLUMN name_fr VARCHAR(255) NULL,
ADD COLUMN name_de VARCHAR(255) NULL,
ADD COLUMN name_es VARCHAR(255) NULL,
ADD COLUMN name_pt VARCHAR(255) NULL;

INSERT INTO lmgc_Countries (name, continent_id, name_en, name_fr, name_de, name_es, name_pt, nota)
VALUES
('Algeria', 1, 'Algeria', 'Algérie', 'Algerien', 'Argelia', 'Argélia', NULL),
('Angola', 1, 'Angola', 'Angola', 'Angola', 'Angola', 'Angola', NULL),
('Benin', 1, 'Benin', 'Bénin', 'Benin', 'Benín', 'Benin', NULL),
('Botswana', 1, 'Botswana', 'Botswana', 'Botswana', 'Botswana', 'Botswana', NULL),
('Burkina Faso', 1, 'Burkina Faso', 'Burkina Faso', 'Burkina Faso', 'Burkina Faso', 'Burquina Faso', NULL),
('Burundi', 1, 'Burundi', 'Burundi', 'Burundi', 'Burundi', 'Burundi', 'Burundi', NULL),
('Cabo Verde', 1, 'Cape Verde', 'Cap-Vert', 'Kap Verde', 'Cabo Verde', 'Cabo Verde', NULL),
('Cameroon', 1, 'Cameroon', 'Cameroun', 'Kamerun', 'Camerún', 'Camarões', NULL),
('Central African Republic', 1, 'Central African Republic', 'République Centrafricaine', 'Zentralafrikanische Republik', 'República Centroafricana', 'República Centro-Africana', NULL),
('Chad', 1, 'Chad', 'Tchad', 'Tschad', 'Chad', 'Chade', NULL),
('Comoros', 1, 'Comoros', 'Comores', 'Komoren', 'Comoras', 'Comores', NULL),
('Congo, Republic of the', 1, 'Congo', 'Congo', 'Kongo', 'Congo', 'Congo', NULL),
('Congo, Democratic Republic of the', 1, 'Democratic Republic of the Congo', 'République Démocratique du Congo', 'Demokratische Republik Kongo', 'República Democrática del Congo', 'República Democrática do Congo', NULL),
('Djibouti', 1, 'Djibouti', 'Djibouti', 'Dschibuti', 'Yibuti', 'Jibuti', NULL),
('Egypt', 1, 'Egypt', 'Égypte', 'Ägypten', 'Egipto', 'Egito', NULL),
('Equatorial Guinea', 1, 'Equatorial Guinea', 'Guinée Équatoriale', 'Äquatorialguinea', 'Guinea Ecuatorial', 'Guiné Equatorial', NULL),
('Eritrea', 1, 'Eritrea', 'Érythrée', 'Eritrea', 'Eritrea', 'Eritreia', NULL),
('Eswatini', 1, 'Eswatini', 'Eswatini', 'Eswatini', 'Esuatini', 'Suazilândia', NULL),
('Ethiopia', 1, 'Ethiopia', 'Éthiopie', 'Äthiopien', 'Etiopía', 'Etiópia', NULL),
('Gabon', 1, 'Gabon', 'Gabon', 'Gabon', 'Gabón', 'Gabon', NULL),
('Gambia', 1, 'Gambia', 'Gambie', 'Gambia', 'Gambia', 'Gâmbia', NULL),
('Ghana', 1, 'Ghana', 'Ghana', 'Ghana', 'Ghana', 'Gana', NULL),
('Guinea', 1, 'Guinea', 'Guinée', 'Guinea', 'Guinea', 'Guiné', NULL),
('Guinea-Bissau', 1, 'Guinea-Bissau', 'Guinée-Bissau', 'Guinea-Bissau', 'Guinea-Bisáu', 'Guiné-Bissau', NULL),
('Ivory Coast', 1, 'Ivory Coast', 'Côte d\'Ivoire', 'Elfenbeinküste', 'Costa de Marfil', 'Costa do Marfim', NULL),
('Kenya', 1, 'Kenya', 'Kenya', 'Kenia', 'Kenia', 'Quênia', NULL),
('Lesotho', 1, 'Lesotho', 'Lesotho', 'Lesotho', 'Lesoto', 'Lesoto', NULL),
('Liberia', 1, 'Liberia', 'Libéria', 'Liberia', 'Liberia', 'Libéria', NULL),
('Libya', 1, 'Libya', 'Libye', 'Libyen', 'Libia', 'Líbia', NULL),
('Madagascar', 1, 'Madagascar', 'Madagascar', 'Madagaskar', 'Madagascar', 'Madagascar', NULL),
('Malawi', 1, 'Malawi', 'Malawi', 'Malawi', 'Malawi', 'Malawi', NULL),
('Mali', 1, 'Mali', 'Mali', 'Mali', 'Mali', 'Mali', NULL),
('Mauritania', 1, 'Mauritania', 'Mauritanie', 'Mauretanien', 'Mauritania', 'Mauritânia', NULL),
('Mauritius', 1, 'Mauritius', 'Maurice', 'Mauritius', 'Mauricio', 'Maurício', NULL),
('Morocco', 1, 'Morocco', 'Maroc', 'Marokko', 'Marruecos', 'Marrocos', NULL),
('Mozambique', 1, 'Mozambique', 'Mozambique', 'Mosambik', 'Mozambique', 'Moçambique', NULL),
('Namibia', 1, 'Namibia', 'Namibie', 'Namibia', 'Namibia', 'Namíbia', NULL),
('Niger', 1, 'Niger', 'Niger', 'Niger', 'Níger', 'Níger', NULL),
('Nigeria', 1, 'Nigeria', 'Nigéria', 'Nigeria', 'Nigeria', 'Nigéria', NULL),
('Rwanda', 1, 'Rwanda', 'Rwanda', 'Ruanda', 'Ruanda', 'Ruanda', NULL),
('Sao Tome and Principe', 1, 'São Tomé and Príncipe', 'São Tomé-et-Príncipe', 'São Tomé und Príncipe', 'São Tomé y Príncipe', 'São Tomé e Príncipe', NULL),
('Senegal', 1, 'Senegal', 'Sénégal', 'Senegal', 'Senegal', 'Senegal', NULL),
('Seychelles', 1, 'Seychelles', 'Seychelles', 'Seychellen', 'Seychelles', 'Seychelles', NULL),
('Sierra Leone', 1, 'Sierra Leone', 'Sierra Leone', 'Sierra Leone', 'Sierra Leona', 'Serra Leoa', NULL),
('Somalia', 1, 'Somalia', 'Somalie', 'Somalia', 'Somalia', 'Somália', NULL),
('South Africa', 1, 'South Africa', 'Afrique du Sud', 'Südafrika', 'Sudáfrica', 'África do Sul', NULL),
('South Sudan', 1, 'South Sudan', 'Soudan du Sud', 'Südsudan', 'Sudán del Sur', 'Sudão do Sul', NULL),
('Sudan', 1, 'Sudan', 'Soudan', 'Sudan', 'Sudán', 'Sudão', NULL),
('Togo', 1, 'Togo', 'Togo', 'Togo', 'Togo', 'Togo', NULL),
('Tunisia', 1, 'Tunisia', 'Tunisie', 'Tunesien', 'Túnez', 'Tunísia', NULL),
('Uganda', 1, 'Uganda', 'Ouganda', 'Uganda', 'Uganda', 'Uganda', NULL),
('Tanzania', 1, 'Tanzania', 'Tanzanie', 'Tansania', 'Tanzania', 'Tanzânia', NULL),
('Zambia', 1, 'Zambia', 'Zambie', 'Sambia', 'Zambia', 'Zâmbia', NULL),
('Zimbabwe', 1, 'Zimbabwe', 'Zimbabwe', 'Simbabwe', 'Zimbabue', 'Zimbábue', NULL);

INSERT INTO lmgc_Countries (name, continent_id, name_en, name_fr, name_de, name_es, name_pt, nota)
VALUES
('Afghanistan', 3, 'Afghanistan', 'Afghanistan', 'Afghanistan', 'Afganistán', 'Afeganistão', NULL),
'Armenia', 3, 'Armenia', 'Arménie', 'Armenien', 'Armenia', 'Arménia', NULL),
'Azerbaijan', 3, 'Azerbaijan', 'Azerbaïdjan', 'Aserbaidschan', 'Azerbaiyán', 'Azerbaijão', NULL),
'Bahrain', 3, 'Bahrain', 'Bahreïn', 'Bahrain', 'Baréin', 'Bahrein', NULL),
'Bangladesh', 3, 'Bangladesh', 'Bangladesh', 'Bangladesch', 'Bangladesh', 'Bangladesh', NULL),
'Bhutan', 3, 'Bhutan', 'Bhoutan', 'Bhutan', 'Bután', 'Butão', NULL),
'Brunei', 3, 'Brunei', 'Brunei', 'Brunei', 'Brunéi', 'Brunei', NULL),
'Cambodia', 3, 'Cambodia', 'Cambodge', 'Kambodscha', 'Camboya', 'Camboja', NULL),
'China', 3, 'China', 'Chine', 'China', 'China', 'China', NULL),
'Cyprus', 3, 'Cyprus', 'Chypre', 'Zypern', 'Chipre', 'Chipre', NULL),
'Georgia', 3, 'Georgia', 'Géorgie', 'Georgien', 'Georgia', 'Geórgia', NULL),
'India', 3, 'India', 'Inde', 'Indien', 'India', 'Índia', NULL),
'Indonesia', 3, 'Indonesia', 'Indonésie', 'Indonesien', 'Indonesia', 'Indonésia', NULL),
'Iran', 3, 'Iran', 'Iran', 'Iran', 'Irán', 'Irã', NULL),
'Iraq', 3, 'Iraq', 'Irak', 'Irak', 'Irak', 'Iraque', NULL),
'Israel', 3, 'Israel', 'Israël', 'Israel', 'Israel', 'Israel', NULL),
'Japan', 3, 'Japan', 'Japon', 'Japan', 'Japón', 'Japão', NULL),
'Jordan', 3, 'Jordan', 'Jordanie', 'Jordanien', 'Jordania', 'Jordânia', NULL),
'Kazakhstan', 3, 'Kazakhstan', 'Kazakhstan', 'Kasachstan', 'Kazajistán', 'Cazaquistão', NULL),
'Kuwait', 3, 'Kuwait', 'Koweït', 'Kuwait', 'Kuwait', 'Kuwait', NULL),
'Kyrgyzstan', 3, 'Kyrgyzstan', 'Kirghizistan', 'Kirgistan', 'Kirguistán', 'Quirguistão', NULL),
'Laos', 3, 'Laos', 'Laos', 'Laos', 'Laos', 'Laos', NULL),
'Lebanon', 3, 'Lebanon', 'Liban', 'Libanon', 'Líbano', 'Líbano', NULL),
'Malaysia', 3, 'Malaysia', 'Malaisie', 'Malaysia', 'Malasia', 'Malásia', NULL),
'Maldives', 3, 'Maldives', 'Maldives', 'Maldiven', 'Maldivas', 'Maldivas', NULL),
'Mongolia', 3, 'Mongolia', 'Mongolie', 'Mongolei', 'Mongolia', 'Mongólia', NULL),
'Myanmar', 3, 'Myanmar', 'Myanmar', 'Myanmar', 'Birmania', 'Myanmar', NULL),
'Nepal', 3, 'Nepal', 'Népal', 'Nepal', 'Nepal', 'Nepal', NULL),
'Oman', 3, 'Oman', 'Oman', 'Oman', 'Omán', 'Omã', NULL),
'Pakistan', 3, 'Pakistan', 'Pakistan', 'Pakistan', 'Pakistán', 'Paquistão', NULL),
'Palestine', 3, 'Palestine', 'Palestine', 'Palästina', 'Palestina', 'Palestina', NULL),
'Philippines', 3, 'Philippines', 'Philippines', 'Philippinen', 'Filipinas', 'Filipinas', NULL),
'Qatar', 3, 'Qatar', 'Qatar', 'Katar', 'Catar', 'Catar', NULL),
'Saudi Arabia', 3, 'Saudi Arabia', 'Arabie Saoudite', 'Saudi-Arabien', 'Arabia Saudita', 'Arábia Saudita', NULL),
'Singapore', 3, 'Singapore', 'Singapour', 'Singapur', 'Singapur', 'Cingapura', NULL),
'South Korea', 3, 'South Korea', 'Corée du Sud', 'Südkorea', 'Corea del Sur', 'Coreia do Sul', NULL),
'Sri Lanka', 3, 'Sri Lanka', 'Sri Lanka', 'Sri Lanka', 'Sri Lanka', 'Sri Lanka', NULL),
'Syria', 3, 'Syria', 'Syrie', 'Syrien', 'Siria', 'Síria', NULL),
'Tajikistan', 3, 'Tajikistan', 'Tadjikistan', 'Tadschikistan', 'Tayikistán', 'Tajiquistão', NULL),
'Thailand', 3, 'Thailand', 'Thaïlande', 'Thailand', 'Tailandia', 'Tailândia', NULL),
'Timor-Leste', 3, 'Timor-Leste', 'Timor-Leste', 'Osttimor', 'Timor-Leste', 'Timor-Leste', NULL),
'Turkey', 3, 'Turkey', 'Turquie', 'Türkei', 'Turquía', 'Turquia', NULL),
'Turkmenistan', 3, 'Turkmenistan', 'Turkménistan', 'Turkmenistan', 'Turkmenistán', 'Turcomenistão', NULL),
'United Arab Emirates', 3, 'United Arab Emirates', 'Émirats Arabes Unis', 'Vereinigte Arabische Emirate', 'Emiratos Árabes Unidos', 'Emirados Árabes Unidos', NULL),
'Uzbekistan', 3, 'Uzbekistan', 'Ouzbékistan', 'Usbekistan', 'Uzbekistán', 'Uzbequistão', NULL),
'Vietnam', 3, 'Vietnam', 'Viêt Nam', 'Vietnam', 'Vietnam', 'Vietnã', NULL),
'Yemen', 3, 'Yemen', 'Yémen', 'Jemen', 'Yemen', 'Iémen', NULL);

INSERT INTO lmgc_Countries (name, continent_id, name_en, name_fr, name_de, name_es, name_pt, nota)
VALUES
('Albania', 4, 'Albania', 'Albanie', 'Albanien', 'Albania', 'Albânia', NULL),
'Andorra', 4, 'Andorra', 'Andorre', 'Andorra', 'Andorra', 'Andorra', NULL),
'Armenia', 4, 'Armenia', 'Arménie', 'Armenien', 'Armenia', 'Arménia', NULL),
'Austria', 4, 'Austria', 'Autriche', 'Österreich', 'Austria', 'Áustria', NULL),
'Azerbaijan', 4, 'Azerbaijan', 'Azerbaïdjan', 'Aserbaidschan', 'Azerbaiyán', 'Azerbaijão', NULL),
'Belarus', 4, 'Belarus', 'Bélarus', 'Weißrussland', 'Bielorrusia', 'Bielorrússia', NULL),
'Belgium', 4, 'Belgium', 'Belgique', 'Belgien', 'Bélgica', 'Bélgica', NULL),
'Bosnia and Herzegovina', 4, 'Bosnia and Herzegovina', 'Bosnie-Herzégovine', 'Bosnien und Herzegowina', 'Bosnia y Herzegovina', 'Bósnia e Herzegovina', NULL),
'Bulgaria', 4, 'Bulgaria', 'Bulgarie', 'Bulgarien', 'Bulgaria', 'Bulgária', NULL),
'Croatia', 4, 'Croatia', 'Croatie', 'Kroatien', 'Croacia', 'Croácia', NULL),
'Cyprus', 4, 'Cyprus', 'Chypre', 'Zypern', 'Chipre', 'Chipre', NULL),
'Czech Republic', 4, 'Czech Republic', 'République tchèque', 'Tschechische Republik', 'República Checa', 'República Checa', NULL),
'Denmark', 4, 'Denmark', 'Danemark', 'Dänemark', 'Dinamarca', 'Dinamarca', NULL),
'Estonia', 4, 'Estonia', 'Estonie', 'Estland', 'Estonia', 'Estónia', NULL),
'Finland', 4, 'Finland', 'Finlande', 'Finnland', 'Finlandia', 'Finlândia', NULL),
'France', 4, 'France', 'France', 'Frankreich', 'Francia', 'França', NULL),
'Georgia', 4, 'Georgia', 'Géorgie', 'Georgien', 'Georgia', 'Geórgia', NULL),
'Germany', 4, 'Germany', 'Allemagne', 'Deutschland', 'Alemania', 'Alemanha', NULL),
'Greece', 4, 'Greece', 'Grèce', 'Griechenland', 'Grecia', 'Grécia', NULL),
'Hungary', 4, 'Hungary', 'Hongrie', 'Ungarn', 'Hungría', 'Hungria', NULL),
'Iceland', 4, 'Iceland', 'Islande', 'Island', 'Islandia', 'Islândia', NULL),
'Ireland', 4, 'Ireland', 'Irlande', 'Irland', 'Irlanda', 'Irlanda', NULL),
'Italy', 4, 'Italy', 'Italie', 'Italien', 'Italia', 'Itália', NULL),
'Kazakhstan', 4, 'Kazakhstan', 'Kazakhstan', 'Kasachstan', 'Kazajistán', 'Cazaquistão', NULL),
'Kosovo', 4, 'Kosovo', 'Kosovo', 'Kosovo', 'Kosovo', 'Kosovo', NULL),
'Latvia', 4, 'Latvia', 'Lettonie', 'Lettland', 'Letonia', 'Letônia', NULL),
'Liechtenstein', 4, 'Liechtenstein', 'Liechtenstein', 'Liechtenstein', 'Liechtenstein', 'Liechtenstein', NULL),
'Lithuania', 4, 'Lithuania', 'Lituanie', 'Litauen', 'Lituania', 'Lituânia', NULL),
'Luxembourg', 4, 'Luxembourg', 'Luxembourg', 'Luxemburg', 'Luxemburgo', 'Luxemburgo', NULL),
'Malta', 4, 'Malta', 'Malte', 'Malta', 'Malta', 'Malta', NULL),
'Moldova', 4, 'Moldova', 'Moldova', 'Moldawien', 'Moldova', 'Moldova', NULL),
'Monaco', 4, 'Monaco', 'Monaco', 'Monaco', 'Mónaco', 'Mônaco', NULL),
'Montenegro', 4, 'Montenegro', 'Monténégro', 'Montenegro', 'Montenegro', 'Montenegro', NULL),
'Netherlands', 4, 'Netherlands', 'Pays-Bas', 'Niederlande', 'Países Bajos', 'Países Baixos', NULL),
'North Macedonia', 4, 'North Macedonia', 'Macédoine du Nord', 'Nordmazedonien', 'Macedonia del Norte', 'Macedônia do Norte', NULL),
'Norway', 4, 'Norway', 'Norvège', 'Norwegen', 'Noruega', 'Noruega', NULL),
'Poland', 4, 'Poland', 'Pologne', 'Polen', 'Polonia', 'Polônia', NULL),
'Portugal', 4, 'Portugal', 'Portugal', 'Portugal', 'Portugal', 'Portugal', NULL),
'Romania', 4, 'Romania', 'Roumanie', 'Rumänien', 'Rumanía', 'Romênia', NULL),
'Russia', 4, 'Russia', 'Russie', 'Russland', 'Rusia', 'Rússia', NULL),
'San Marino', 4, 'San Marino', 'Saint-Marin', 'San Marino', 'San Marino', 'San Marino', NULL),
'Serbia', 4, 'Serbia', 'Serbie', 'Serbien', 'Serbia', 'Sérvia', NULL),
'San Marino', 4, 'San Marino', 'Saint-Marin', 'San Marino', 'San Marino', 'San Marino', NULL),
'Sweden', 4, 'Sweden', 'Suède', 'Schweden', 'Suecia', 'Suécia', NULL),
'Switzerland', 4, 'Switzerland', 'Suisse', 'Schweiz', 'Suiza', 'Suíça', NULL),
'Turkey', 4, 'Turkey', 'Turquie', 'Türkei', 'Turquía', 'Turquia', NULL),
'Ukraine', 4, 'Ukraine', 'Ukraine', 'Ukraine', 'Ucrania', 'Ucrânia', NULL),
'United Kingdom', 4, 'United Kingdom', 'Royaume-Uni', 'Vereinigtes Königreich', 'Reino Unido', 'Reino Unido', NULL),
'Vatican City', 4, 'Vatican City', 'Vatican', 'Vatikanstadt', 'Ciudad del Vaticano', 'Vaticano', NULL);

INSERT INTO lmgc_Countries (name, continent_id, name_en, name_fr, name_de, name_es, name_pt, nota)
VALUES
('Antigua and Barbuda', 5, 'Antigua and Barbuda', 'Antigua-et-Barbuda', 'Antigua und Barbuda', 'Antigua y Barbuda', 'Antígua e Barbuda', NULL),
'Bahamas', 5, 'Bahamas', 'Bahamas', 'Bahamas', 'Bahamas', 'Bahamas', NULL),
'Barbados', 5, 'Barbados', 'Barbade', 'Barbados', 'Barbados', 'Barbados', NULL),
'Belize', 5, 'Belize', 'Belize', 'Belize', 'Belice', 'Belize', NULL),
'Canada', 5, 'Canada', 'Canada', 'Kanada', 'Canadá', 'Canadá', NULL),
'Cuba', 5, 'Cuba', 'Cuba', 'Kuba', 'Cuba', 'Cuba', NULL),
'Dominica', 5, 'Dominica', 'Dominique', 'Dominica', 'Dominica', 'Dominica', NULL),
'Dominican Republic', 5, 'Dominican Republic', 'République dominicaine', 'Dominikanische Republik', 'República Dominicana', 'República Dominicana', NULL),
'El Salvador', 5, 'El Salvador', 'El Salvador', 'El Salvador', 'El Salvador', 'El Salvador', NULL),
'Grenada', 5, 'Grenada', 'Grenade', 'Grenada', 'Granada', 'Granada', NULL),
'Guatemala', 5, 'Guatemala', 'Guatemala', 'Guatemala', 'Guatemala', 'Guatemala', NULL),
'Haiti', 5, 'Haiti', 'Haïti', 'Haiti', 'Haití', 'Haiti', NULL),
'Honduras', 5, 'Honduras', 'Honduras', 'Honduras', 'Honduras', 'Honduras', NULL),
'Jamaica', 5, 'Jamaica', 'Jamaïque', 'Jamaika', 'Jamaica', 'Jamaica', NULL),
'Mexico', 5, 'Mexico', 'Mexique', 'Mexiko', 'México', 'México', NULL),
'Nicaragua', 5, 'Nicaragua', 'Nicaragua', 'Nicaragua', 'Nicaragua', 'Nicarágua', NULL),
'Panama', 5, 'Panama', 'Panama', 'Panama', 'Panamá', 'Panamá', NULL),
'Saint Kitts and Nevis', 5, 'Saint Kitts and Nevis', 'Saint-Christophe-et-Niévès', 'Saint Kitts und Nevis', 'San Cristóbal y Nieves', 'São Cristóvão e Névis', NULL),
'Saint Lucia', 5, 'Saint Lucia', 'Sainte-Lucie', 'St. Lucia', 'Santa Lucía', 'Santa Lúcia', NULL),
'Saint Vincent and the Grenadines', 5, 'Saint Vincent and the Grenadines', 'Saint-Vincent-et-les-Grenadines', 'Saint Vincent und die Grenadinen', 'San Vicente y las Granadinas', 'São Vicente e Granadinas', NULL),
'United States', 5, 'United States', 'États-Unis', 'Vereinigte Staaten', 'Estados Unidos', 'Estados Unidos', NULL);

INSERT INTO lmgc_Countries (name, continent_id, name_en, name_fr, name_de, name_es, name_pt, nota)
VALUES
'Argentina', 7, 'Argentina', 'Argentine', 'Argentinien', 'Argentina', 'Argentina', NULL),
'Bolivia', 7, 'Bolivia', 'Bolivie', 'Bolivien', 'Bolivia', 'Bolívia', NULL),
'Brazil', 7, 'Brazil', 'Brésil', 'Brasilien', 'Brasil', 'Brasil', NULL),
'Chile', 7, 'Chile', 'Chili', 'Chile', 'Chile', 'Chile', NULL),
'Colombia', 7, 'Colombia', 'Colombie', 'Kolumbien', 'Colombia', 'Colômbia', NULL),
'Ecuador', 7, 'Ecuador', 'Équateur', 'Ecuador', 'Ecuador', 'Equador', NULL),
'Guyana', 7, 'Guyana', 'Guyane', 'Guyana', 'Guyana', 'Guiana', NULL),
'Paraguay', 7, 'Paraguay', 'Paraguay', 'Paraguay', 'Paraguay', 'Paraguai', NULL),
'Peru', 7, 'Peru', 'Pérou', 'Peru', 'Perú', 'Peru', NULL),
'Suriname', 7, 'Suriname', 'Suriname', 'Suriname', 'Surinam', 'Suriname', NULL),
'Uruguay', 7, 'Uruguay', 'Uruguay', 'Uruguay', 'Uruguay', 'Uruguai', NULL),
'Venezuela', 7, 'Venezuela', 'Venezuela', 'Venezuela', 'Venezuela', 'Venezuela', NULL);

INSERT INTO lmgc_Countries (name, continent_id, name_en, name_fr, name_de, name_es, name_pt, nota)
VALUES
'Australia', 6, 'Australia', 'Australie', 'Australien', 'Australia', 'Austrália', NULL),
'Fiji', 6, 'Fiji', 'Fidji', 'Fidschi', 'Fiyi', 'Fiji', NULL),
'Kiribati', 6, 'Kiribati', 'Kiribati', 'Kiribati', 'Kiribati', 'Kiribati', NULL),
'Marshall Islands', 6, 'Marshall Islands', 'Îles Marshall', 'Marshallinseln', 'Islas Marshall', 'Ilhas Marshall', NULL),
'Micronesia', 6, 'Micronesia', 'Micronésie', 'Mikronesien', 'Micronesia', 'Micronésia', NULL),
'Nauru', 6, 'Nauru', 'Nauru', 'Nauru', 'Nauru', 'Nauru', NULL),
'New Zealand', 6, 'New Zealand', 'Nouvelle-Zélande', 'Neuseeland', 'Nueva Zelanda', 'Nova Zelândia', NULL),
'Palau', 6, 'Palau', 'Palaos', 'Palau', 'Palaos', 'Palau', NULL),
'Papua New Guinea', 6, 'Papua New Guinea', 'Papouasie-Nouvelle-Guinée', 'Papua-Neuguinea', 'Papúa Nueva Guinea', 'Papua-Nova Guiné', NULL),
'Samoa', 6, 'Samoa', 'Samoa', 'Samoa', 'Samoa', 'Samoa', NULL),
'Solomon Islands', 6, 'Solomon Islands', 'Îles Salomon', 'Salomonen', 'Islas Salomón', 'Ilhas Salomão', NULL),
'Tonga', 6, 'Tonga', 'Tonga', 'Tonga', 'Tonga', 'Tonga', NULL),
'Tuvalu', 6, 'Tuvalu', 'Tuvalu', 'Tuvalu', 'Tuvalu', 'Tuvalu', NULL),
'Vanuatu', 6, 'Vanuatu', 'Vanuatu', 'Vanuatu', 'Vanuatu', 'Vanuatu', NULL);
